### ISSUE TITLE
add isZero, isPZero, isNZero, isPositive, isNegative checks

### ISSUE THREAD

**Issue by mantkiew** [LeventErkok/sbv#132]
These are useful and currently (4.2) missing checks. Based on [SMT-LIB2 FloatingPoint](http://smtlib.cs.uiowa.edu/theories/FloatingPoint.smt2):

```
(fp.isZero (_ FloatingPoint eb sb) Bool)
 
    [[fp.isZero]](x) = true iff x is positive or negative zero.
```

```
(fp.isNegative (_ FloatingPoint eb sb) Bool)

    [[fp.isNegative]](x) = true iff x is [[-zero]] or [[fp.lt]](x, [[-zero]]) holds.
```

```
(fp.isPositive (_ FloatingPoint eb sb) Bool)

    [[fp.isPositive]](x) = true iff x is [[+zero]] or [[fp.lt]]([[+zero]], x) holds.
```

and `isPZero = isZero && isPositive`, `isNZero = isZero && isNegative`

See also [StackOverflow Question](http://stackoverflow.com/questions/29283304/how-to-get-rid-of-solutions-with-0-0-in-sbv) whereby the proposed solution slows down solving a lot.

Also, these were mentioned in a closed issue #69.

**Comment by LeventErkok** [comment]
@mantkiew Yes, I noticed those in #69, but apparently forgot about them afterwards. I'll add these in the next release. (I'm waiting for a new MathSAT release first, see #131, which will also support floating-point; I want to test both Z3 and MathSAT before the next release is out). Thanks for the note.

**Comment by LeventErkok** [comment]
This is now implemented, adding the predicates:
    
       * isNormalFP
       * isSubnormalFP
       * isZeroFP
       * isInfiniteFP
       * isNaNFP
       * isNegativeFP
       * isPositiveFP
       * isNegativeZeroFP
       * isPositiveZeroFP
       * isPointFP

Two caveats:

- A few bugs fixed in Z3 just this morning are required for these two work. Pull from their unstable branch, and expect other possible breakage; it's "unstable" for a reason. It's best to keep up-to-date with Z3 on a daily basis if you're using the floating-point theory.

- There's a GHC bug (https://ghc.haskell.org/trac/ghc/ticket/10215), which makes `isPositiveZeroFP` behave incorrectly when passed the constant -0. This should be a relatively low impact bug, but keep in mind that until that bug is closed in GHC the isPositiveZeroFP predicate should not be 100% trusted.
