### ISSUE TITLE
CNF support

### ISSUE THREAD

**Issue by weaversa** [LeventErkok/sbv#183]
Feature request ---

Now that `abc` supports SMTLIB2 and is supported as a solver by SBV, CNF files could be generated via it's `write_cnf` command. This could enable generic SAT solver support for SBV via the SAT competition format (http://www.satcompetition.org/2009/format-solvers2009.html).

**Comment by LeventErkok** [comment]
@weaversa Since SBV can already spit out SMT-Lib (via https://github.com/LeventErkok/sbv/blob/fba7db001e7d47d02ea671158c6dfd080f762539/Data/SBV/Provers/Prover.hs#L315) I'm wondering if it's best left to the user to take that output and feed it to ABC for other conversions.

Let me know if that solution is not sufficient/does not work for any reason; and we can add the necessary functionality accordingly.

**Comment by LeventErkok** [comment]
I'm convinced that this isn't quite the right thing to do directly from within SBV.

ABC is a large system with many facilities and functions; picking and choosing to expose just one feature of it seems arbitrary, though the current request is probably well-justified.

Going through `compileToSMTLib` and using ABC offline to do all sorts of transformations on the generated benchmark seems to be the right thing to do here.
