### ISSUE TITLE
sbv-5.9 test suite failure

### ISSUE THREAD

**Issue by peti** [LeventErkok/sbv#211]
Citing from http://hydra.cryp.to/build/1517735/log/raw:

~~~~
Running 1 test suites...
Test suite SBVBasicTests: RUNNING...
Cases: 297732  Tried: 297732  Errors: 0  Failures: 2
*** SBVBasicTester, version: 5.9, time stamp: Tue Jan  5 17:59:03 PST 2016
*** Starting SBV basic tests..
*** Gold files at: "/tmp/nix-build-sbv-5.9.drv-0/sbv-5.9/SBVUnitTest/GoldFiles"
*** Running 17 test categories.
Starting category: "arithCF"
*** 2 (of 297732) test cases failed.
Test suite SBVBasicTests: FAIL
~~~~~

**Comment by LeventErkok** [comment]
@peti Thanks for the report. I'm confident that this is because of #138, which in turn is caused by: https://ghc.haskell.org/trac/ghc/ticket/9238

The bad news is that this test will fail for GHC <= 7.10.2; which this particular machine seems to be using. The good news is that the bug is fixed in GHC 7.10.3.

Is there a way you can upgrade to 7.10.3 and rerun the test-suite?

**Comment by peti** [comment]
You are right, with GHC 7.10.3 the issue disappears. Thank you very much for the quick response!

**Comment by LeventErkok** [comment]
Glad to hear!
