### ISSUE TITLE
Pretty-printing smt output with String and (++) is slow and uses too much memory

### ISSUE THREAD

**Issue by brianhuffman** [LeventErkok/sbv#216]
I did some profiling of SBV and Cryptol using the `AESCorrect` example from GaloisInc/cryptol#189, which generates a large (~22 MB) SMTLib output and spends most of its time in the garbage collector. Profiling shows that a significant amount of allocation is done by pretty-printing functions that concatenate strings. For example, `cvt.mkLet` from `Data.SBV.SMT.SMTLib2` performs 14.3% of all allocation by itself (35.7% inherited).

We should replace the use of type `String` and `(++)` with something more efficient, both in terms of time and space.

**Comment by LeventErkok** [comment]
Agreed. This is one of those things that started "simple" and got out of hand.

While the consumer of the output is almost always the machine, I'd like the output to be sufficiently indented to be easy to read by humans; helps greatly in debugging.

I'd be OK with using SimonPJ/Hughes pretty-printing combinators; or go via Iavor's `smtLib` package; whichever is easier. Latter should be preferred I guess; but if it doesn't support everything we need, then maybe it can also be upgraded enroute to do so. (I didn't see support for inserted comments for instance, but perhaps it wouldn't be too hard to add those.)

I trust you guys will be sending a patch? Happy to apply!

**Comment by robdockins** [comment]
While working on GaloisInc/cryptol#354, I put together some SBV patches that reduced space usage somewhat.  These changes include: using the hashtable package for term caches; using the strict `modifyIORef'` method; and swapping out `String` for lazy text builders in the SMT pretty printer.
I've pushed these changes into a branch: https://github.com/robdockins/sbv/tree/space-reduction

Ultimately, the improvements due to these changes were swamped by simply increasing the GC nursery size, but I thought I'd post them here anyway in case @LeventErkok wants to pull some of them.

**Comment by LeventErkok** [comment]
@robdockins @brianhuffman 

Thanks guys! I'll keep this ticket open, though I don't intend to pull in any changes without good reason. To be fair, Cryptol is the most important customer of SBV (that I know off at least), and if you guys are happy with the current performance, I don't see an immediate need to make changes to risk bugs/unforeseen issues.

Feel free to commit a patch, however, if you think it'll help Cryptol.

**Comment by LeventErkok** [comment]
@robdockins I don't think this is an issue any longer? I'll close this but we can revisit later if necessary.
