### ISSUE TITLE
Declaring identical lookup tables with different index types produces type-incorrect smtlib

### ISSUE THREAD

**Issue by brianhuffman** [LeventErkok/sbv#218]
See GaloisInc/cryptol#327 for an example. When two lookups with different index bit-widths are used, there should be two separate tables in the generated smtlib. However, SBV is incorrectly merging them together and generating only one table.

It looks like the source of the problem is `getTableIndex` in `SBV/BitVectors/Symbolic.hs`. The hash-consing there only considers the elements of the lookup table, and does not check whether the argument type matches.

**Comment by LeventErkok** [comment]
@brianhuffman Looks like we came up with a similar solution; but you beat me to it in committing.

The difference between mine and yours was that I put both the `at` and `rt` into the key for `TblMap`: This way we're indexing on both of those; as opposed to just indexing by `at` as in your example.

Semantics-wise, I think putting `rt` in the key isn't going to gain anything, because elements would surely differ if they weren't the same type. But there's one curious gotcha: The case of empty-list! When the table is empty, you can still screw yourself up by not putting the `at` in there. Having said that, I think if the table is actually empty then SBV wouldn't have generated it anyhow (all look-ups would fail), so your solution would've worked just fine. But I like this version better due to the symmetry in its treatment of the argument/result kinds.

What do you think?

**Comment by brianhuffman** [comment]
Hmm, I never thought about an empty list. Should SBV even declare an smtlib table at all in that case? Anyway, if you want to put `rt` in the map keys as well, that's fine by me.

**Comment by LeventErkok** [comment]
Yeah, as I mentioned it probably has an optimization to skip the table if it's empty; but I like this version better due to its symmetry. Should we drop that optimization one day for whatever reason, this'll provide a safeguard against that pathological case.
