### ISSUE TITLE
minimise with binary search?

### ISSUE THREAD

**Issue by tomjaguarpaw** [LeventErkok/sbv#227]
Have you considered implementing (a version of) `minimize` using binary search?  It could mean that the optimum is found much more quickly.

**Comment by LeventErkok** [comment]
It's definitely possible to customize the search algorithm; though binary-search doesn't work for infinite types like `SInteger` or `SReal`. And for `SFloat` and `SDouble` there would be stability issues.

The idea is that `minimize`/`maximize` just provide the most basic interface, that potentially works for all types. Different problems/domains probably admit much better optimization strategies, which the user is then free to implement on her own as need. You can look at the code for these functions yourself: https://github.com/LeventErkok/sbv/blob/060b800837601f9f284883441396b55af1ace8c9/Data/SBV/Tools/Optimize.hs and adopt for your own needs. There's nothing in these functions that cannot be done at the user level. (Let me know if you find otherwise!)

**Comment by LeventErkok** [comment]
@tomjaguarpaw NB. Also see #223. While SBV does not support this for the time being, you might want to try your hand at trying `Z3Opt` directly, depending on your needs. And perhaps integrate it into SBV later on. Patches welcome.
