### ISSUE TITLE
Add support for `int2bv` and `bv2int` functions

### ISSUE THREAD

**Issue by brianhuffman** [LeventErkok/sbv#233]
These smtlib functions are supported to some extent by Z3 and other solvers. It would be useful for SBV to provide coercions between `SInteger` and `SWord*` types that map onto the these functions.

Such a feature would be particularly useful for implementing an `Integer` type in Cryptol (GaloisInc/cryptol#347).

**Comment by LeventErkok** [comment]
@brianhuffman 

SBV already supports this via `sFromIntegral`; is there a problem with it? (Maybe you need to add it to the dynamic interface, if not already there?)

Also note that `int2bv` goes essentially uninterpreted in Z3: http://stackoverflow.com/questions/22326466/z3-an-exception-with-int2bv

So you're opening the possibility of getting bogus-counterexamples and the users will have almost no warning (unless you add it explicitly) that this is happening.

Let me know if  there's an issue with `sFromIntegral`.

**Comment by brianhuffman** [comment]
Oh, I didn't know about `sFromIntegral`! I simply grepped the sbv sources for "int2bv" and "bv2int" and didn't find anything. I will need to add this to the dynamic interface.

Looking at the source, I see that the `b2i` and `i2b` coercions are implemented by extracting individual bits (with `extract` or `div`/`mod`) and then concatenating them back together (with `concat` or `+` and `ite`). While this has the correct semantics, I'd imagine that Z3 would bog down a bit on large bit sizes. For example, imagine trying to prove `int2bv (x * y) = int2bv x * int2bv y` at 128 bits. It might be nice to have *some* way of producing Z3's native `int2bv` and `bv2int` functions.

**Comment by LeventErkok** [comment]
I've forgotten that I did the `i2b` and `b2i` that way.

I think my main motivation was that `int2bv` will go uninterpreted anyhow; so our translation is better. (Mind you, I think the reason they leave it uninterpreted is precisely because it's so expensive.)

For `b2i`, I can't recall why I didn't use `bv2int`; perhaps I thought both were uninterpreted?

In either case, I don't think you'll get much performance out of these functions, whether you go through the native versions or use the current translations. I suggest we punt on this and do the conversions if you come across cases where the current translation is not adequate. Going to the uninterpreted land can really confuse things a lot for non-suspecting users.

Of course, experiments are always welcome. Perhaps you have some spare cycles to play around with it. Patches are always welcome.
