### ISSUE TITLE
test-suite, quiet mode doesn't seem to work?

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#284]
@kanishka-azimi 

When I run the new test suite with the "-q" parameter, it seems to go to sleep! Do you observe the same? Here's the command I'm trying:

            ./dist/build/int-test-extended/int-test-extended -q -p '**' -j 4

and the process just goes to sleep.

**Comment by LeventErkok** [comment]
I'm wondering  if this modification somehow impacts how the `-q` parameter works:

   https://github.com/LeventErkok/sbv/blob/master/SBVUnitTest/SBVIntTest.hs#L38-L44

I don't know why it should, but just a question.

**Comment by kanishka-azimi** [comment]
I haven't forgotten about this. I just had a busy week last week. I will comment here once I get some time between tasks.

Overall, I use `stack test` instead of `cabal test` or running the test executable produced by cabal, so what gets suppressed can be slightly different. I will try to install cabal and ghc directly somewhere, so I reproduce exactly what you are seeing.

**Comment by LeventErkok** [comment]
@kanishka-azimi Great! Thanks for looking into this. I'm still puzzled about the behavior.

I'm on a Mac, not that it should matter for this.

**Comment by LeventErkok** [comment]
@kanishka-azimi This still seems to be an issue, but it's a curiosity at the moment. I'll close this ticket, though if you have any idea why this is happening, I'd love to know!
