### ISSUE TITLE
Documentation still references `tactic` which was removed in 7.0

### ISSUE THREAD

**Issue by mpickering** [LeventErkok/sbv#336]
The documentation still references `tactic` which was removed in 7.0. 

It seems the correct fix is to rewrite your code in terms of `Data.SBV.Control`.

**Comment by mpickering** [comment]
I want to essentially call the `z3` tactic `ctx-solver-simplify` in order to simplify a set of constraints. I can't find anywhere in the interface which allows me to call a custom tactic like this. 

Is this possible with the current interface?

What would be required to add this option to the interface?

**Comment by LeventErkok** [comment]
There are two main ways to communicate the tactic. If all you need is a one-way-communication with the solver, simply set it in the configuration:

```
proveWith z3{satCmd = "(check-sat-using ctx-solver-simplify)"} $ \x -> x .== (x::SWord8)
```

This will work just as usual, except will send the specific command you give in the call to check-sat. I'd prefer this method if that's all you need, as it's the simplest.

As you observed, if you need something more programmable, i.e., get the results, inspect, send further commands down, then you should use the `checkSatUsing` function in the query mode: https://hackage.haskell.org/package/sbv-7.4/docs/Data-SBV-Control.html#v:checkSatUsing. 

Query mode is a little trickier to use, but it gives you the power to send arbitrary commands, inspect results etc. Let me know if you come across any issues. 

You are correct that the "tactic" mechanism is replaced with queries with SBV 7.0. If you can point me to the part of the documentation that's still referring to the old content, I'll make sure it gets fixed.

**Comment by mpickering** [comment]
Thanks @LeventErkok for your detailed and helpful reply.

I experimented for a bit using `check-sat-using` and I don't think it does what I want. 

The intent of using `ctx-solver-simplify` is to first assert lots of constraints with redundancies. Then use `(apply ctx-solver-simplify)` to reduce the number of goals. Then I want to manipulate the new goals as normal Haskell values. 

I can't see a way of using `check-sat-using` which allows me to retrieve the unsatisfied goals after applying it. `getModel` etc all fail as `ctx-solver-simplify` leaves an unsolved goal (as desired) and hence `check-sat` returns unknown. 

Am I missing a way to achieve what I want with the library or is this out of scope?

**Comment by LeventErkok** [comment]
Looks like you really need to be in the `Query` mode then. And you'd want to use the following two functions:

[sendStringToSolver](https://hackage.haskell.org/package/sbv-7.4/docs/Data-SBV-Internals.html#v:sendStringToSolver)
[sendRequestToSolver](sendRequestToSolver)

Both of these allow you to send arbitrary commands down to the solver (in your case "apply"), and also optionally get a response back with the latter. The down-side is they operate with strings, so you'll have to do further processing on those to proceed as you might. And of course they will be solver-specific and thus fragile; unfortunately. That's why these functions are both exported from [Data.SBV.Internals](https://hackage.haskell.org/package/sbv-7.4/docs/Data-SBV-Internals.html) module, instead of the higher-level API.

If you can create a "common use case" pattern with a nice API around it (i.e., instead of sending down-returning strings, some appropriate data-type), please consider making a patch and we can add it to the [Data.SBV.Control](https://hackage.haskell.org/package/sbv-7.4/docs/Data-SBV-Control.html) module as a higher-level API.

**Comment by mpickering** [comment]
That did the trick.

How is the best way to parse the resulting string? It doesn't look like from `Data.SBV.Utils.SExpr.parseSExpr` is exported.

**Comment by LeventErkok** [comment]
I debated exporting that functionality quite a bit, but decided against it since it seemed too SBV internals specific, with all it's `AlgReal` etc. nodes, and I wasn't sure how useful that would be for processing arbitrary output from a solver.

Perhaps this can be used: https://hackage.haskell.org/package/sexpr Seems generic enough.

I wouldn't be opposed to exporting the internal parser/data-type from the Internals module, but I imagined people would use something different based on how they wanted to proceed. Let me if trying an external parser is not an option and we can export it then.

**Comment by LeventErkok** [comment]
@mpickering Is there any further action to take on this ticket? If you are able to generalize from your example and add an API for `apply` like functionality to SBV, please submit a patch. I'm happy to discuss the details, though being extremely Z3 specific makes me hesitate. Otherwise, I suggest we close this ticket.

**Comment by mpickering** [comment]
The suggestions in this ticket work fine for my use case. There are still the references to `tactic` in the documentation though. 

For example under the headings:

Named constraints and unsat cores
Checking for vacuity

**Comment by LeventErkok** [comment]
Ah, good point. I'll do a scan and clean-up later this weekend.

**Comment by LeventErkok** [comment]
I think I removed all obsolete references. Please report any others you might come across. Thanks.
