### ISSUE TITLE
`SInteger` shouldn't be used with `sTestBit`?

### ISSUE THREAD

**Issue by TomMD** [LeventErkok/sbv#337]
I noticed testing bits of an integer results in `intSizeOf` being called on the sinteger type and this isn't either 1. documented or 2. prevented by the exposed api.

```
*Main> main
*** Exception: SBV.HasKind.intSizeOf((S)Integer)
CallStack (from HasCallStack):
  error, called at ./Data/SBV/Core/Kind.hs:120:36 in sbv-7.4-9Uc4O1nrlOCEM12MDXkzmH:Data.SBV.Core.Kind
```

When running:

```
import Data.SBV
import Data.List

main :: IO ()
main = print =<< seenil

seenil :: IO (Maybe Integer)
seenil = getModel <$> optimize Independent (do
    x <- sInteger "x"
    constrain (x .> 2)
    constrain (bnot (sTestBit x 0))
    minimize "goal" x)

getModel (LexicographicResult r)      = head <$> extractModel r
getModel (ParetoResult (_,r:_))       = head <$> extractModel r
getModel (IndependentResult ((_,r):_)) = head <$> extractModel r
getModel _                            = Nothing
```

**Comment by LeventErkok** [comment]
@TomMD Thanks for the report. The fundamental issue here is that in Haskell `Integer` is `Bits`, but not in SMT-Lib. (You cannot inspect bits of an SMTLib `Int` value.) So, were being a bit loose about the types, allowing things to type-check though they wouldn't really work in practice.

I bit the bullet and added a `SFiniteBits` class, and tweaked type signatures of a bunch of functions accordingly. Your example now fails to type-check since `sTestBit` wants a finite bit. Use the following instead:
 
      x `sMod` 2 .== 1

The correspondence between Haskell/SMT-Lib isn't perfect unfortunately. Also, Haskell's `FiniteBits` class didn't exist when SBV was first coded up, I wish we had that insight before-hand.

In any case, I think the current changes improve the situation. Please give it a test and let me know if you find any gotchas.

**Comment by LeventErkok** [comment]
@TomMD Did you get a chance to try this out? Would like to close the ticket if it's no longer an issue.

**Comment by LeventErkok** [comment]
@TomMD I'm planning to do a release in the next week or so and would like to make sure the concerns are addressed before doing so.

**Comment by LeventErkok** [comment]
SBV 7.5 will be released soon; I'm closing this ticket as I think this release addresses it. If not, please feel free to reopen!

**Comment by TomMD** [comment]
Oh I looked and thought "that is a wonderful solution" then failed to respond.  Thanks Levent!
