### ISSUE TITLE
Code generation misses some opportunities to eliminate constants

### ISSUE THREAD

**Issue by peddie** [LeventErkok/sbv#379]
If I write

    g :: SBool
    g = (0 :: SInt64) .< (-22 :: SInt64)

and generate the corresponding C code, SBV cleverly emits a constant:

    void g(SBool *bool_out)
    {
      *bool_out = false;
    }

If I write a slightly more complicated program

    f :: SInt8 -> SBool
    f int = (0 :: SInt64) .< (ite (int ./= int) (0 :: SInt64) (-9223372036854775808 :: SInt64) :: SInt64)

SBV's C code looks like this:

    void f(const SInt8 integer, SBool *bool_out)
    {
      const SBool s3 = 0x0000000000000000LL < INT64_MIN;

      *bool_out = s3;
    }

So it is able to see that `int ./= int` is always `false`, but in this case, it doesn't perform the optimization it performed on `g` to eliminate the comparison of two literal constant values.  It should.

**Comment by LeventErkok** [comment]
Something to do with `./=`; because `.==` works just fine. But I haven't figured it out yet.

Note that this has nothing to do with code-generation, but rather how SBV internally processes the expressions. So, you'd have observed the same thing sent to the SMT solver in `sat`/`prove` mode as well.

**Comment by LeventErkok** [comment]
Here's a somewhat simpler example, that doesn't go through the C generator:

```
Prelude Data.SBV> proveWith z3{verbose=True} $ \x -> 0 .< ite (x .== (x::SWord8)) 1 (2::SWord8)
** Calling: z3 -nw -in -smt2
[GOOD] ; Automatically generated by SBV. Do not edit.
[GOOD] (set-option :print-success true)
[GOOD] (set-option :global-declarations true)
[GOOD] (set-option :smtlib2_compliant true)
[GOOD] (set-option :diagnostic-output-channel "stdout")
[GOOD] (set-option :produce-models true)
[GOOD] (set-logic QF_BV)
[GOOD] ; --- uninterpreted sorts ---
[GOOD] ; --- literal constants ---
[GOOD] (define-fun s_2 () Bool false)
[GOOD] (define-fun s_1 () Bool true)
[GOOD] (define-fun s1 () (_ BitVec 8) #x00)
[GOOD] (define-fun s2 () (_ BitVec 8) #x01)
[GOOD] ; --- skolem constants ---
[GOOD] (declare-fun s0 () (_ BitVec 8))
[GOOD] ; --- constant tables ---
[GOOD] ; --- skolemized tables ---
[GOOD] ; --- arrays ---
[GOOD] ; --- uninterpreted constants ---
[GOOD] ; --- user given axioms ---
[GOOD] ; --- formula ---
[GOOD] (define-fun s3 () Bool (bvult s1 s2))
[GOOD] (assert (not s3))
[SEND] (check-sat)
[RECV] unsat
*** Solver   : Z3
*** Exit code: ExitSuccess
Q.E.D.
```

There's no reason why this generates the call to `bvult`, the constant folding mechanism should be able to deal with this.

**Comment by LeventErkok** [comment]
The issue comes down to how `symbolicMerge` is implemented:

https://github.com/LeventErkok/sbv/blob/master/Data/SBV/Core/Operations.hs#L491-L492

We're hitting the case where the test isn't concrete, but rather becomes `True`/`False` during symbolic evaluation. (i.e., the test of the if-then-else ends up being `trueSW` (or `falseSW`). But, by that time we're already inside the `Right` branch of an `SVal`; i.e., we have lost the "constantness" of the result. Thus we end up creating a new symbolic constant and returning an `SW` handle to it.

This is rather unfortunate. But also quite tricky to handle in full. One can argue that such tests shouldn't really happen very often, as writing `x .== x` is not a common thing to do! I'd like to think some more about this; but we might end up ignoring this as a corner unoptimized case.

@peddie Can you imagine a real-world scenario where this sort of an expression might crop up? I'm pretty sure no manually written code will ever employ this, but SBV is typically used as a backend in many code-analysis systems and generated code can definitely have such bizarre expressions. I'd like to know if this is a real issue anywhere or not. And what the actual impact might be. Any feedback is most appreciated.

**Comment by peddie** [comment]
@LeventErkok This came up for me when using a property-based testing library to generate random expressions in a first-order arithmetic language, so it's not a particularly real-world situation in my application.  Since the semantics of the C still seems correct, not having this optimization doesn't bother me.

I think one way a sensible handwritten program could potentially produce this situation might be via SBV's hash-consing, where we know a value is being compared to itself under the hood but it's not immediately apparent to the user.

**Comment by LeventErkok** [comment]
@peddie 

There is a way to "fix" this, but unfortunately it's not cheap. I've added some comments here: https://github.com/LeventErkok/sbv/commit/ea6bd4b876d3ea803f8f1d079c4eefca8d7e5b2f#diff-9f10584b300368db321d5af23eb5d3e6R869

Since the cost of checking for such opportunities doesn't seem to justify the savings it would bring, I'm inclined to leave the implementation as is. (Bottom line, we would have to check at every single operation whether a constant is hiding beneath an SW. That is quite a hit for every symbolic result!)

However, please report if you ever come across a case where this missed constant folding becomes a real issue in practice. Even if we might not have a solution, it is important to capture such scenarios so a future design might take it into account. And thanks so much for reporting it in the first place!
