### ISSUE TITLE
Incorporate Hedgehog tests

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#388]
@peddie 

This is a placeholder ticket for Matt to integrate his hedgehog tests into SBV.

I've never heard of Hedgehog before, but it seems to be compatible with quickcheck. We already have a few quickcheck tests in this file: https://github.com/LeventErkok/sbv/blob/master/SBVTestSuite/TestSuite/QuickCheck/QC.hs

Feel free to either add them there (and have them all run by hedgehog I suppose), or create a new file (or multiple files) in that directory, whatever makes the most sense.

We do have a way of running these only locally since CI is unlikely to support such heavy loads. The code is here:  https://github.com/LeventErkok/sbv/blob/master/SBVTestSuite/SBVTest.hs#L118-L132

However, these are just some guidelines. Feel free to arrange your tests as it makes the most sense.

**Comment by peddie** [comment]
Thanks for creating this.  

An outline of what I'm doing in our internal system
-----------------------

 1) Generating random expressions using Hedgehog
 2) Generating input vectors using Hedgehog
 2) Emitting the C code corresponding to these expressions using SBV
 3) Shelling out to the compiler to create a shared object that contains the compiled generated function
 4) Loading the shared object with `dlopen()` so I can call the compiled code from Haskell
 5) Calling the SBV expression and the compiled C code on the input vectors
 6) Comparing the results

Notes for myself
-----------

(to remember what questions to look into for doing the same thing standalone in SBV.)

 - The reason to use `dlopen()` rather than generating static files is so that Hedgehog can shrink the expressions as well as the inputs.  In the internal system, it's never able to reduce all the way to minimal examples, but it does usually reduce massively from the initial expression in which it found the bug.

 - All the C functions the internal system generates have the same calling convention (one input array of each base type and one output array of each base type), which is a very limited subset of SBV's.  This makes using `dlopen()` easy, since I always know the function type.  Can this trick even be done without a type that's known ahead of time?  How could we make the right `foreign import ccall "dynamic"` declaration?

 - The internal expression generation is quite fancy / contorted and leans heavily on the Haskell type system to make sure we can never generate an ill-typed expression by mistake.  It also operates on a fixed set of base types (i.e. there's no equivalent of a "user sort", and there are no strings).  The user-facing SBV API has a lot of this type safety, so similarly, we shouldn't have to touch the internal representation and risk making a mistake -- but can the internal approach work for everything in `Kind` that can be used in code-generation?

Feedback welcome.  It's not necessary to start by implementing all the functionality described above, but without any of it, the internal system would be much less helpful.

**Comment by LeventErkok** [comment]
Sounds fantastic! I'm looking forward to seeing what this will entail and what other bugs it'll no doubt find.

**Comment by LeventErkok** [comment]
This is unlikely to happen, so closing till someone who's really familiar with hedgehog needs it and has the time to do so.
