### ISSUE TITLE
GHCJS interface

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#424]
@bts to fill in!

**Comment by bts** [comment]
Now that [FFI dependencies have been removed from sbv](https://github.com/LeventErkok/sbv/pull/420#issuecomment-439634881), it seems the major missing component is to abstract away the details of solver process execution behind an interface, and create an implementation of this interface that talks with a backend that executes the solver over the network. Because we'd like this interface to support interactive (i.e. non-batch) use of the solver process, it needs to be stateful. The best option here seems to be WebSockets.

In https://github.com/LeventErkok/sbv/pull/420 we can see the work which creates a `SolverProcess` interface, and `startExecutableProcess` which provides the existing local solver functionality in terms of this interface.

In https://github.com/bts/sbv/tree/solver-process3 (if you ignore the latest "WIP" commit) we can see the work which builds on this to create (1) a WebSocket-based server and (2) a server-side WebSocket-client implementation of `SolverProcess` for testing (and I suppose use outside of the browser). The remaining two pieces of work that remain here are:

(1) a GHCJS-based WebSocket client
(2) extraction of the work on the `solver-process3` branch into a new project (or two or three; depending on how we want to split up server vs client vs shared/common packages), so that we can spare sbv a bunch of new dependencies (e.g. `websockets`, `network`, `bytestring`, `safe`, `wai`, `wai-websockets`, `http-types`)

**Comment by bts** [comment]
If someone were to deploy this in a production use-case, they would also want take some extra precautionary steps to make sandbox/secure z3 and probably put some resource constraints into place as well. As it stands, the WebSocket-based server partially addresses this last point by taking configuration to limit the number of concurrent connections to the server.

**Comment by LeventErkok** [comment]
@bts Thanks for the write-up! It'll have to be someone who "needs" this to implement it; but it's great that you captured the most salient points. Hopefully it'll get done!

**Comment by LeventErkok** [comment]
This is unlikely to ever happen; so closing till someone needs it.
