### ISSUE TITLE
Support for strings in the SBV.Dynamic API

### ISSUE THREAD

**Issue by rodamber** [LeventErkok/sbv#465]
Hi! 

Is there any way to create an SVal of Kind KString (both literals and variables)?
Data.SBV.Core.Operations exports svString, but I can't see any way to do this in Data.SBV.Dynamic.

Moreover, it would be nice to have operations over those, like the ones in Data.SBV.String.

**Comment by LeventErkok** [comment]
Thanks for the comment. The short answer is that there's no support for `SString` in the dynamic interface, and unless there's a really good reason, there are no plans to add such support either. The same goes for types `SFloat`, `SDouble`, `SList`, `SChar`, `SString`, `SSet`,  `STuple`, `SMaybe`, and `SEither` etc., which are mainly available through the typed API.

I'll expand on this a bit so as to serve as documentation of why; I'm always willing to be convinced otherwise or hear about cases where such facilities are needed.

The obvious reason is of course to keep the API as typed as possible, avoiding the dynamic interface if at all possible. This is in the spirit of Haskell. Supporting everything dynamically causes code/API explosion, and introduces complexity that is hard to maintain without an obvious ROI. This is essentially the same reason Haskell has `Dynamic` types, but the user really has to opt-in and they remain second-class citizens and rightly so.

In my mind, the only absolute use case for the dynamic interface to access arbitrary bit-vector sizes. SBV supports bit-vectors of arbitrary lenghts, but only `SIntN` and `SWordN` for `N = 8, 16, 32, 64` are available through the typed-API. For others (i.e. `SWord24`, or `SInt128`), you go through the dynamic interface. The reason for this is mostly historical: Support for data-kinds in Haskell were non-existent when SBV first started about a decade ago, and by the time we can reliably do `SInt N` as a type in Haskell, SBV already had a large code base with lots of internal invariants. Switching over would require an entire rewrite. If this is your use case, then by all means use `SVal` and the dynamic interface; and I hope everything you need is already available.

Another reason why people use the dynamic interface is to be able to put "different" symbolic variable types in one data-structure; like a map or list that can contain differently typed values. For this use case you can always import `Data.SBV.Internals` and peel off the SBV constructor and add it back and forth to do your bidding. I think this should cover all the other use cases. Here's an example using strings:

```haskell
import Data.SBV
import Data.SBV.Dynamic
import Data.SBV.String

import Data.SBV.Internals

-- dynamically decide whether to return to append the inputs or not depending on
-- the third argument. Note that we expect the first two args to be strings
-- and the last to be a boolean; if you violate that, things will go wrong!
foo :: [SVal] -> SVal
foo [s1, s2, i] = svIte i s12 s1
   where -- here we marshall to the typed API and back by slapping on
         -- the SBV constructor and then taking it off.
         s12 = unSBV $ (SBV s1 .++ SBV s2 :: SString)

test :: Goal
test = do s1 <- sString "s1"
          s2 <- sString "s2"
          i  <- sBool "b"

          -- mix and match:
          let r = foo [unSBV s1, unSBV s2, unSBV i]

          constrain $ SBV r .== literal "hello world"
```

When I run `test` I get:

```
*Main> sat test
Satisfiable. Model:
  s1 =          "h" :: String
  s2 = "ello world" :: String
  b  =         True :: Bool
```

I hope this "trick" is sufficient to handle your use case and you use SBV as intended via its fully typed API. Do let me know if your use case cannot be handled using this trick.

**Comment by rodamber** [comment]
Thank you very much for the reply. It makes perfect sense.

Do you think it might make sense to put a version of the above in the docs?

**Comment by LeventErkok** [comment]
It's kind of strewn around, but I'll see if I can improve the dynamic documentation in the upcoming days.

Feel free to post other questions here if you have any trouble in coding with SBV. Cheers.
