### ISSUE TITLE
Option to disable `parenDeficit` check

### ISSUE THREAD

**Issue by JoeyEremondi** [LeventErkok/sbv#475]
I'm using SBV as a backend for some SMT-solving that I'm doing. I have large problems, most of which involve functions over large numbers booleans, and as such, the expression trees are quite deep.

My program is very slow, and after profiling, I've determined that roughly **33%** of my execution time is spent in `parenDeficit`, and the `tokenize` calls within that.

I'm going to try to refactor my code so that it's a large number of small trees, rather than deep trees. But given that the parens check is purely there for sanity, it would be nice to have an option to disable it.

**Comment by LeventErkok** [comment]
Interesting; I've never seen parenthesis-checking being a bottleneck.

There are two places where we check the parenthesis: When we are sending down a command, and when we're receiving back. We can't really skip the latter since solvers can put responses in multiple lines; but I just pushed in a commit that skips it while we're sending it down.

I'd be interested in hearing if this helps.

**Comment by LeventErkok** [comment]
@JoeyEremondi 

I'm assuming this has taken care of the issue; if not please feel free to submit another. I'm interested in hearing about performance issues in SBV.
