### ISSUE TITLE
Cancelling a thread running an runSMT action leaves zombie solver process

### ISSUE THREAD

**Issue by arrowd** [LeventErkok/sbv#477]
In my application I run two `runSMT` actions in parallel using `async` package:

```
sikForTMax <- async $ do
        sik <- runSMT $ do
            ...

sikForDU <- async $ do
        sik <- runSMT $ do
            ...

waitAnySuccessCatch 0 [sikForTMax, sikForDU]
```

where `waitAnySuccessCatch` waits for first successfully finished `Async` job and cancels another using `cancel`.

I run this code in a loop, and during every iteration a new `z3` process in `zombie` state appears in my `ps` output. These processes are unkillable, but they all disappear together when my application finishes.

**Comment by LeventErkok** [comment]
I believe this is expected; and you need to kill those threads explicitly. I remember having similar issues when I implemented `proveWithAny`, `proveWithAll` etc. See this discussion here: https://stackoverflow.com/questions/24446154/control-concurrent-async-race-and-runinteractiveprocess

Otherwise, I don't think this is an SBV related question. Is there something SBV can do to help out?

**Comment by arrowd** [comment]
Maybe SBV should do that

> combination of onException and terminateProcess

 under the hood?

**Comment by LeventErkok** [comment]
It already does when you use `proveWithAll`, `proveWithAny`, etc. See: https://github.com/LeventErkok/sbv/blob/811499a4bb80bd2ecab5733eb4ecb5d037c538fb/Data/SBV/Provers/Prover.hs#L695-L718

The issue here is that you *are* calling `async` yourself. And I see your motivation, since you want to parallelize query mode calls, not calls to `prove` or `sat`. So, you have to arrange for the same. Note that your program is "wrapping" over the SBV call in the IO monad; so it's really up to you to arrange for the proper termination of children thus spawned.

**Comment by arrowd** [comment]
I didn't quite get the difference, but OK, I'll do that on my side.

Thanks for StackOverflow pointer.

**Comment by arrowd** [comment]
I'm a bit puzzled. First, I don't see any `onException` and `terminateProcess` in your code.

Second, I haven't found a way to obtain `ProcessHandle` for the running solver process. I tried using `exit`, but it is in `Query` monad and I need to unlift it into `IO` somehow to be able to use it with `onException`.

Can you help me with that, please?

**Comment by LeventErkok** [comment]
are you doing a `throwTo (asyncThreadId pid) TheadKilled` for the other pid? That should solve the problem.

If not; do send a minimal example I can run stand-alone; as usual, without a running example I can play with it's hard to figure out what might be going wrong.

**Comment by arrowd** [comment]
> are you doing a throwTo (asyncThreadId pid) TheadKilled for the other pid? That should solve the problem.

I was doing `cancel pid`. I replaced it with `throwTo pid ThreadKilled`, but that changed nothing.

I still a bit confused how that's related to intial `onException`+`terminateProcess` approach.

**Comment by LeventErkok** [comment]
SBV code evolved over time; so I don't think I use the `onException` trick anymore. But you can probably go back in history (around 2014 or so?) and find that code.

Let's do one thing: I want to make sure if SBV is involved in this or not. Can you do the following:

```haskell 
   
       r1 <- async $ something that involves call to runInteractiveProcess
       r2 <- asycn $ something that involves call to runInteractiveProcess

```

But do *not* call `runSMT`. Put in around all the other code you have for dealing with the killing of the targets etc. (You can call "sleep 1000"/"sleep 500" etc., to make it independent of SBV.)

Let's see if this set-up gives rise to zombies. If it doesn't, then perhaps SBV is doing something bad. We can take it from there.

**Comment by arrowd** [comment]
After some fruitless experimentation I got an idea that these zombies come up when solver is busy on `check-sat` call. I'm now trying to come up with small yet hard problem for `runSMT` to verify this. Do you have any problems that take 5-10 seconds to solve by hand?

**Comment by LeventErkok** [comment]
I know this one takes a while to solve: https://github.com/LeventErkok/sbv/blob/master/Documentation/SBV/Examples/Existentials/Diophantine.hs
