### ISSUE TITLE
Symbolic newtype values can't be compared with (.<)

### ISSUE THREAD

**Issue by lachrimae** [LeventErkok/sbv#505]
I'm having an issue with doing symbolic operations on newtypes. The example code in [this repository](https://github.com/lachrimae/sbv-newtypes) compiles and throws a runtime error. The runtime error is detailed in README.md.

Version numbers: 
SBV 8.6
GHC 8.8.2
Stack 2.1.3.1
Cabal 3.0.1.0
Z3 4.8.8

**Comment by LeventErkok** [comment]
Can you create a standalone single file that exhibits the issue. That'd be much easier to debug for me.

**Comment by lachrimae** [comment]
Sure. You can check the repo again for SBV_newtypes.hs. The command to build and run is in the README.

**Comment by LeventErkok** [comment]
The problem here is that `SMetres` is not the symbolic version of `Metres`.  Instead, when you do all the `deriving` clauses, you get an uninterpreted domain for `Metres`. Ideally this program shouldn't type-check, but it's currently impossible to avoid that due to how Haskell classes are structured. But perhaps SBV can give a better run-time error message.

You can see for yourself that `SMetres` is uninterpreted by running:

```haskell
Main> sat $ \x -> x .== (x::SMetres)
Satisfiable. Model:
  s0 = Metres!val!0 :: Metres
```

what this is telling you is that `Metres` is an uninterpreted type, and the solver decided to give you one member of it, called `Metres!val!0`. The documentation for this feature is here: https://hackage.haskell.org/package/sbv-8.6/docs/Data-SBV.html#g:36

So, there's no bug here; just that the error-message is utterly confusing and unfortunate.

Your next question would be how to make a newtype like this symbolic. I assume you wanted this type to essentially be `SInteger`.  To do so, you need to explicitly give `HasKind` and `SymVal` instances yourself; like this:

```haskell
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE ScopedTypeVariables        #-}

import Data.SBV
import qualified Data.SBV.Internals as SI

newtype Metres = Metres Integer deriving (Real, Integral, Num, Enum, Eq, Ord)
type SMetres   = SBV Metres

instance HasKind Metres where
   kindOf _ = KUnbounded

instance SymVal Metres where
   mkSymVal = SI.genMkSymVar KUnbounded
   literal  = SI.genLiteral  KUnbounded
   fromCV   = SI.genFromCV
```

Now you can code your formula:

```haskell
formula :: Symbolic SBool
formula = do x :: SInteger <- exists "x"
             y :: SInteger <- exists "y"
             w :: SMetres  <- exists "length"

             constrain $ x .< 13
             constrain $ w .< literal (Metres 13)
             return $ 3 * x + 4 * y .== 0
```

And get a satisfying instance:

```haskell
*Main> sat formula
Satisfiable. Model:
  x      =  0 :: Integer
  y      =  0 :: Integer
  length = 12 :: Integer
```
Hope this gets you started! Let me know if you run into further issues.

**Comment by lachrimae** [comment]
That works perfectly. Thanks for the assistance. Would you be interested in a pull request adding something like this to `Documentation/SBV/Examples/`?

**Comment by LeventErkok** [comment]
Absolutely! This'd be a nice example to add.

**Comment by LeventErkok** [comment]
We can now close this issue, I believe.
