### ISSUE TITLE
Marking inputs as outputs

### ISSUE THREAD

**Issue by arrowd** [LeventErkok/sbv#509]
I was solving a problem using SBV, which solution looked like

```
Satisfiable. Model:
  x1       =   0 :: Word32
  x2       =   0 :: Word32
...
  y1       = 144 :: Word32
  y2       = 144 :: Word32
```

I was extracting these values with `extractModel :: SatResult -> Maybe [Word32]`.

Now I changed the problem a bit, so that `y` values are now of `Word8` type. I still get a solution

```
Satisfiable. Model:
  x1       =   0 :: Word32
  x2       =   0 :: Word32
...
  y1       = 144 :: Word8
  y2       = 144 :: Word8
```

but for obvious reasons I can't conveniently extract whole model as a `[Word32]` anymore - types differ. However, I actually have no need in `y`s.

I tried marking `x`s variables with `output` inside `Symbolic` computation, but this lead to error

> *** Exception: User error: Multiple output values detected

Is there any easy way to exclude `y`s from the model, so I don't have to manually extract `x`s?

**Comment by arrowd** [comment]
I just found that SBV successfuly extracts this model into `([Word32], [Word8])`.

But the question stays - is it possible to use `extractModel` to extract partial models?

**Comment by LeventErkok** [comment]
(Note: `output` relates to C-code generation, and should not be used in this context.)

Yes.. There are two different ways to achieve this. First, you can use the `isNonModelVar` parameter to the config. Something like:

```haskell
satWith z3{isNonModelVar = ("y" `isPrefixOf`)}
```

this should elide any model variable that starts with `y`. Of course, you can give here any definition you like, it's simply a `String -> Bool` function.

However, I'd recommend against using `extractModel` and its friends. These are rather old SBV constructs. While I expect they will be supported in perpetuity, the "modern" way of extracting models like this is to use the query mode, and program it yourself in any way you like. An example is here: https://hackage.haskell.org/package/sbv-8.6/docs/src/Documentation.SBV.Examples.Queries.AllSat.html#demo

Once you are in the query mode, you simply use the symbolic variables themselves (not their names) to query the solver for their values. This avoids the need for naming them (you can still do so if you want of course) and gives you utmost control on what you want to extract and what you want to leave behind.

I find `isNonModelVar` to be a "cheap" solution that works most of the time and does the right thing. But for anything complicated, I'd invest in learning and using the query mode; which has other advantages and gives you more control on how you communicate with the solver. (Especially regarding incremental solving.)

Give this a try and let me know if you see any issues.

**Comment by arrowd** [comment]
Thanks for explanations.

**Comment by arrowd** [comment]
> However, I'd recommend against using extractModel and its friends. These are rather old SBV constructs. While I expect they will be supported in perpetuity, the "modern" way of extracting models like this is to use the query mode, and program it yourself in any way you like.

But "old" way allows using `allSat` to get a list of possble solutions. Is there a way to achieve the same with query mode?

**Comment by LeventErkok** [comment]
In the query mode, you program your own `allSat`, by inspecting values and adding blocking constraints. Something like this should get you started:

```haskell
import Data.SBV
import Data.SBV.Control

foo :: IO [(Integer, Integer)]
foo = runSMT $ do x <- sInteger "x"
                  y <- sInteger "y"
                  constrain $ x .> 0
                  constrain $ x .< 5
                  constrain $ y .> 0
                  constrain $ x + y .== 7

                  let getMore sofar = do cs <- checkSat
                                         case cs of
                                           Unsat -> pure sofar
                                           Unk   -> error "Solver said unknown"
                                           Sat   -> do xv <- getValue x
                                                       yv <- getValue y
                                                       constrain $ x ./= literal xv .|| y ./= literal yv
                                                       getMore $ (xv, yv) : sofar

                  query $ getMore []
```

When I run this, I get:

```haskell
*Main> foo
[(1,6),(2,5),(3,4),(4,3)]
```

Of course, the query mode has all the extra commands for you to navigate this interaction. (i.e., you can add arbitrary constraints, inspect values and decide when to stop instead of going all the way, etc.), so it's much more flexible at the cost of a bit more programming.

**Comment by arrowd** [comment]
Yes, I understand that I can do this myself, I was just hoping for something built-in.

Thanks for examples.

**Comment by arrowd** [comment]
Sorry for bumping this again. For some reason I thought that `allSat` was returning solutions lazily, but now I checked the documentation and it says that `allSat` blocks until all solutions are found. Your `getMore` works the same in this regard.

Is there something that prevents obtaining list of solutions in lazy fashion?

**Comment by LeventErkok** [comment]
That's right. The behavior changed a while ago. See the release notes for details on why: https://github.com/LeventErkok/sbv/blob/master/CHANGES.md#version-70-2017-07-19

* You can use the `allSatMaxModelCount` parameter to set how many (maximum) models you want to get, in case there is an infinite number of them.

* You can use the `allSatPrintAlong` parameter which will print the models as they are found. This is good if you are simply running `allSat` and viewing the output, instead of using them programmatically.

If you want to restore the "lazy" behavior of `allSat`, you can code that yourself in the query mode; it would require you to pass a continuation into the query code you write that "calls back" with each new result: The receiver can then return with a response indicating whether your query should seek more solutions, or stop, or do something else. This is more programming obviously, but it gives you the utmost flexibility.
