### ISSUE TITLE
Array definitions forgotten by `resetAssertions`

### ISSUE THREAD

**Issue by MrChico** [LeventErkok/sbv#535]
From what I can understand, the way sbv encodes array expressions is different from the way other expressions are encoded:
If I have a `x :: SInteger` and define `y = x + 1` the smt var corresponding to y will be `(define-fun sY () Int (+ sX 1))`, whereas if I start with the array `c :: SArray SInteger SInteger` and define `d = writeArray c 1 1`, the smt var corresponding to `d` will be a fresh array `(declare-fun array_1 () (Array Int Int))` constrained by `(assert (= array_1 (store 1 1 array_0))`.

With the former encoding, I can use `y` in any point in my queries but with the latter, the definition of `d` is basically forgotten after a call to `resetAssertions`.

In my use case for symbolic execution of a vm, this causes some state updates to be forgotten while symbolically exploring paths, leading to incompleteness.

Would it be feasible to make the encoding of arrays consistent with that of other expressions so that `resetAssertions` won't effect term definitions?

**Comment by doyougnu** [comment]
This looks like intended behavior to me based on the theory of arrays in `SMTLIB2` [here](http://smtlib.cs.uiowa.edu/theories-ArraysEx.shtml), there is a better example in the `z3` `rise4fun` docs [here](https://rise4fun.com/Z3/tutorialcontent/guide#h26).

But essentially with this kind of relational-constraint based programming the only way for the solver to know anything about the array is through an assertion of a constraint. Thus, the array itself is never actually _holding_ a value or anything like that, and when you call `resetAssertions` it correctly removes the constraints which define the behavior of your symbolic array.

Is it possible for you to construct a toy example of your use case? I suspect you might be better off using a Haskell array of `SBV a`'s rather than a symbolic array but I am not really sure what your use case mandates.

**Comment by LeventErkok** [comment]
Jeff is correct to point out this is how assertions work in SMTLib; but I do think Martin is making a good point as well: If we're defining a new array we should make sure its definition stays unchanged through calls to `resetAssertions`. After all, the user didn't create the constraint; it's SBV that did it on user's behalf.

Before we get into solution space, however, I think Jeff is absolutely right we should think about what the use cases are. Here's an example I thought of:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}

import Data.SBV
import Data.SBV.Control

q = do x :: SArray Integer Integer <- newArray "x" Nothing
       let y = writeArray x 0 1

       query $ do constrain $ readArray y 0 .== 2
                  io . print =<< checkSat

                  resetAssertions

                  constrain $ readArray y 0 .== 2
                  io . print =<< checkSat
```

Currently, I get:

```haskell
*Main> runSMT  q
Unsat
Sat
```

It is rather surprising that we get different answers here. (The reason is we translate the definition of `y` in terms of assertions which get lost as Jeff points out.)

In particular, it isn't that you want your own `constrain` calls to survive `resetAssertions`, but you do expect those introduced by SBV when it defines the array `y` in the above example to survive.

And I believe this is the main issue. Is that correct @MrChico?

**Comment by MrChico** [comment]
N.b. that my issue would be resolved if array_1 was defined as:
```
(define-fun array_1 () (Array SInteger SInteger) (store 1 1 array_0))
```
instead of using asserts. Since definitions are global, but assertions are forgotten with `resetAssertions`, I can use array_1 as intended 

I can not make a toy example at the moment, but as I am writing abd reading from symbolic locations I cannot use a haskell array for my use case.

**Comment by MrChico** [comment]
Yes @LeventErkok thats exactly right.

In my use case, one of the reasons I'm using query and resetAssertions is because I want to explore different paths if its possible for a value to be 1, and another if its possible for a value to be 0, and both if both are possible. The queries are separated by a resetAssertions, but now the latter would always be satisfiable.

**Comment by LeventErkok** [comment]
Thanks Martin, good to have clarification here.

Based on this, I'd call this an SBV bug in `resetAssertions`, as it "forgets" internal constraints.

The reason why we create these constraints has to do with quantifiers and delayed actions that might come from skolemization; but the details of that is obviously internal to SBV and nothing that the user should know or care about. Let me see if I can find a solution.

In the meantime, note that `SFunArray` of SBV (which does not use SMTLib arrays) shouldn't suffer from this problem; as it internally manages arrays and is not impacted by `resetAssertions`. Can you use `SFunArray` as a workaround? (One downsize: You cannot compare `SFunArray`'s for equality, so if you need array-equality checks they won't work for you.) If possible, give that a try and lets see if addresses the immediate issue.

**Comment by MrChico** [comment]
Hmm, I currently do check the arrays for equality. I could possible still use `SFunArray` if I manually keep track of the entries touched and check each entry, but it would require some restructuring in the code. I think I will hold off for a bit and see if this becomes necessary, but I appreciate the advice!

**Comment by LeventErkok** [comment]
@MrChico 

Upon investigation, this is actually the same issue as #374. There, we had the exact same problem with `push`/`pop`. Your case is exhibiting the same issue with `resetAssertions`. Good catch!

I should be able to adopt that solution here as well, hopefully that'll be sufficient.

**Comment by LeventErkok** [comment]
@MrChico I pushed in changes which should address the issue with `resetAssertions`. You should be able to use `SArray`, i.e., no changes needed on your side.

Can you give it a try and confirm whether it's working for you?

**Comment by MrChico** [comment]
@LeventErkok I just tried it out and the issue seems to be resolved indeed! Thanks for the quick fix!

**Comment by LeventErkok** [comment]
Great.. I'll make a release on hackage soon.

**Comment by LeventErkok** [comment]
SBV 8.7, fixing this issue, is now on Hackage. https://hackage.haskell.org/package/sbv-8.7

Thanks for the report.
