### ISSUE TITLE
ExtractIO looks like MonadUnliftIO

### ISSUE THREAD

**Issue by arrowd** [LeventErkok/sbv#537]
I stumbled upon [ExtractIO](https://hackage.haskell.org/package/sbv-8.6/docs/Data-SBV-Control.html#t:ExtractIO) typeclass and to me it seems to be a reimplementation of [MonadUnliftIO](https://hackage.haskell.org/package/unliftio-core-0.2.0.1/docs/Control-Monad-IO-Unlift.html#t:MonadUnliftIO) from `unliftio` package.

Perhaps it'd make sense to reuse existing package?

**Comment by LeventErkok** [comment]
This was Brian's work (@bts), and he's done such a wonderful job in adding transformable symbolic layers to SBV that I'd trust he either didn't know about that package, or maybe there's some fundamental difference.

I'm in general against adding new dependencies, especially for "small" things that already work well. But I'll leave it to @bts to take a look and decide if the move would be justified. (To be fair, I haven't heard from Brian in a while, so I'm not sure if he's going to respond. Let's see if he does.)

**Comment by LeventErkok** [comment]
@arrowd Looks like @bts is no longer working on these, and I don't feel comfortable enough to modify the code.

If you're interested, you're more than welcome to send a PR with the required modification: If all the test suite passes, I'd be happy to merge it in.

**Comment by doyougnu** [comment]
For what it is worth when i was experimenting with `MonadBaseControl` from the `monad-control` package and sbv I also had this thought. But I think it could be rather tricky because you have to be careful not to _actually run_ the IO computation when you unlift it, if you do then I think `sbv` will lose state, or worse it will try to re-introduce variables in the `SBV foo` computation. I ran into this in particular when trying to make query operations concurrent but decided it was unnecessary complexity, and IMHO avoiding an extra dependency is probably worth an extra type class.
