### ISSUE TITLE
Using SArray instead of static Array of `SBV` elements is massively slower

### ISSUE THREAD

**Issue by gergoerdi** [LeventErkok/sbv#546]
According to our discussion [on StackOverflow](https://chat.stackoverflow.com/transcript/message/49865833#49865833), it seems using `SArray` instead of a fixed array or list of `SBV` variables shouldn't slow things down ([it's even supposed to be faster](https://stackoverflow.com/a/62798538/477476)).  However, this is not what I'm seeing on my small test project.

In https://github.com/gergoerdi/scottcheck/tree/c48bb38c3c99e8e89301e37267ee009063ff62ea I change my stateful computation's state from `Array Int16 SInt16` to `SArray Int16 Int16`. I run it for the included sample input `games/t4.sao` on the same machine before and after that single change, using `ts -i %s` to show the time elapsing between output lines:

`Array Int16 SInt16`:

```
1 Searching at depth: 1
0 Searching at depth: 2
15 Searching at depth: 3
44 Searching at depth: 4
72 Searching at depth: 5
102 Searching at depth: 6
150 Searching at depth: 7
166 Searching at depth: 8
189 Searching at depth: 9
256 Searching at depth: 10
282 Searching at depth: 11
307 Searching at depth: 12
339 Searching at depth: 13
```

`SArray Int16 Int16`:

```
1 Searching at depth: 1
49 Searching at depth: 2
190 Searching at depth: 3
344 Searching at depth: 4
```

(and then I killed it)

**Comment by doyougnu** [comment]
I am not sure this is completely unexpected behavior. 

I would expect `Array` to be faster because with `Array` you are not asking the backend solver to do anything extra, you are just pulling a symbolic value from memory for use in a assertion. With `SArray` you're effectively adding more constraints to the backend solver which determine what is in the `SArray` this means the backend solver has to search to find the value (that you just lookup in the `Array` case) that should be at a the particular index in the `SArray`. Secondly, I would expect `Array` to be subject to more optimizations by ghc whereas `SArray` cannot be subject to such optimizations as it is defining an action in the backend solver, although that is likely not what is happening here.

**Comment by LeventErkok** [comment]
Jeff is right.. There's no way an `SArray a b` will be as fast as `Array a (SBV b)`, not even by a long shot. If the latter is usable (i.e., if there are no symbolic indexes), then it should always be preferred. Even if you use an `SArray a b` and always index with concrete values (i.e., indexes of the form `literal x`), I'd expect visible slowdown.

This doesn't mean, however, we can't improve. Jeff is the expert at profiling SBV and performance considerations actually, so I'm happy he's looking into this. Perhaps we can create a sample problem and Jeff can profile it? It might be possible to identify some hotspots in SBV that can make dramatic improvements. I'll let Jeff take a look at that repo and see if there's anything we can do, but obviously this is of lower priority and totally depends on Jeff's personal time and continued interest in SBV, which is much appreciated.

(NB. #541 is different of course: Regardless of speed, that needs to be fixed.)

**Comment by gergoerdi** [comment]
> Jeff is right.. There's no way an `SArray a b` will be as fast as `Array a (SBV b)`, not even by a long shot. If the latter is usable (i.e., if there are no symbolic indexes), then it should always be preferred. Even if you use an `SArray a b` and always index with concrete values (i.e., indexes of the form `literal x`), I'd expect visible slowdown.

But [my SO question](https://stackoverflow.com/q/62794803/477476) is about indexing with symbolic values! And the recommendation I got was to try `SArray`s.

Now granted, I am not actually replacing these `sCase` programs with `SArray`s yet, but that is because I wanted to try it out at a smaller scale first. But please do note that the arrays I am replacing with an `SArray` in the linked commit are very much indexed symbolically.

**Comment by gergoerdi** [comment]
At the very least, could someone comment on the validity of my remark on the SO answer:

> Wow, this is completely the opposite of my naive intuition: I would have thought that having a statically known structure of symbolic values is more efficient than a symbolic structure. – Cactus [Jul 9 at 2:54[(https://stackoverflow.com/questions/62794803/efficient-way-to-do-n-ary-branch-tabulated-functions/62798538#comment111066801_62798538)

**Comment by LeventErkok** [comment]
If there's no symbolic indexing or look-up, a structure that has static known structure is always faster. There's no doubt about that.

I recommended using `SArray` (and `SFunArray` if it works!) only if the static structure isn't possible since you need to write to symbolic indexes. That is, only when there's no other way to solve the problem. But perhaps things got lost in translation and I misled you to think otherwise. To be clear, if there's no symbolic indexing into the array, always use a good-old Haskell Array, not `SArray` or `SFunArray`.

I'm still interested to see what Jeff thinks about the slowdown and if there's anything we can do about it. As a rough rule of thumb, I'd expect all symbolic array indexing to be linear in the #-of-elements in the array. (Of course, `merge`'s complicate things.) If you're observing undue slowdown, it'd be good to see why.

Note that Jeff also has a framework for measuring SBV and Z3 costs separately. That can also shed some light into the whole story.

**Comment by gergoerdi** [comment]
> To be clear, if there's no symbolic indexing into the array, always use a good-old Haskell Array, not `SArray` or `SFunArray`.

I'd like to keep stressing that yes, **I am using symbolic indexing** and I keep **updating symbolically-indexed values in the array**. So please keep the recommendations coming for that use case:)

**Comment by LeventErkok** [comment]
Absolutely.. The whole point is symbolic access. And with that constraint, it's normal that `SArray` adds cost. This is why I'm interested in profiling the run and see if we can hot-spots. (It *will* be slow, but hopefully still useful!)

If you're asking whether we can define a different data-structure that has better performance characteristics for symbolic indexing: It's unlikely, but you might want to look into `STree`:  https://hackage.haskell.org/package/sbv-8.7/docs/Data-SBV-Tools-STree.html

These are "full" binary trees with fixed shape. They are indexed by bit-vectors of "small" enough size. (Say 10-12 bits or so.) Each tree will have 2^n elements for an n-bit index. (But you can use `SMaybe` for elements and put `sNothing` where it doesn't exist.) When you do symbolic access, it'll bit-blast the address and walk down the height, and thus is supposed to be more efficient. You can do symbolic reads and writes.

Depending on your needs, you can perhaps use `STree`, or at least look at how it's implemented and design your own structure that works the best for you. (Note that `STree` is implementable by the user, SBV knows nothing specific about them; you could've written that code on top of SBV.)

Note that if you can keep your index as a blasted set of bits yourself, you can do even better: If some of those bits are concrete, then that'll automatically speed things up. (In the SAT world, this happens. But in the general SMT word, this is usually not possible as values are either fully symbolic or fully concrete, without any "concrete" subparts.)

**Comment by doyougnu** [comment]
I think this is where the confusion is though, when you have `Array Int16 SInt16` you are indexing by an `Int16`, but `SArray Int16 Int16` is indexing by an `SBV Int16`, so the code you have above is comparing a non-symbolic index with a symbolic index.

You can see this in the definition of `SArray` and it's instance in `SymArray`:
```
newtype SArray a b = SArray { unSArray :: SArr }

instance (HasKind a, HasKind b) => Show (SArray a b) where
  show SArray{} = "SArray<" ++ showType (Proxy @a) ++ ":" ++ showType (Proxy @b) ++ ">"

instance SymArray SArray where
  readArray   (SArray arr) (SBV a)               = SBV (readSArr arr a)
  writeArray  (SArray arr) (SBV a)    (SBV b)    = SArray (writeSArr arr a b)
  mergeArrays (SBV t)      (SArray a) (SArray b) = SArray (mergeSArr t a b)
```
`a` and `b` are just phantom types in the `SArray` definition, but all the operations for `SArray` are actually `SBV` values.

Regarding your comment in SO, I don't think the response you received concludes that statically known structure of symbolic values is less efficient (in time) than symbolic structure. It seems to me that the response you received states that symbolic lookups will be expensive regardless of the data structure you use, and that you can translate from static structures to symbolic ones depending on your use case. I'm not saying there will not be or are not cases where using a symbolic structure is faster, there very well may be, but in your example this doesn't seem to be the case.

An example program such as the one in #541 would be much appreciated though. It is possible that the code you have right now is creating a lot of thunks in Symbolic or Query state due to a lot of merging, or if you are lazily folding with `foldr` instead of having a strict accumulating such as with `foldr'`. Either way, we would need to benchmark your code to be sure.

**Comment by LeventErkok** [comment]
@gergoerdi Completely agreed with Jeff. A sample program to do some profiling would be most helpful.

**Comment by gergoerdi** [comment]
> I think this is where the confusion is though, when you have `Array Int16 SInt16` you are indexing by an `Int16`, but `SArray Int16 Int16` is indexing by an `SBV Int16`, so the code you have above is comparing a non-symbolic index with a symbolic index.

Yeah but I index into that `Array` via [this](https://github.com/gergoerdi/scottcheck/blob/ee8d656e1aa2305b6e2f385e9f7a90532196fe52/src/ScottCheck/Utils.hs#L10) operator:

```
(.!) :: (Mergeable a) => Array Int16 a -> SInt16 -> a
xs .! i = case A.elems xs of
    [] -> error "(.!) : empty array"
    xs@(x:_) -> select xs x i
```

**Comment by LeventErkok** [comment]
It's really hard to reason about performance in general, and SBV definitely adds an extra layer of complexity to go through.

I think the best course of action is to rely on Jeff's expertise in profiling. (I think he's the only person who ever successfully profiled SBV and got insights into it. My earlier trials never went anywhere.  So kudos to him!)

@gergoerdi Let's create a benchmark that he can work on. Perhaps he can take a stab at some github commit point? The smaller the program the better of course, but the ask here is not for you to create something that's absolute minumum.

**Comment by gergoerdi** [comment]
Although it is hard to start simplifying a program when I have absolutely no idea where the performance problems could possibly be, I will come back to this to make a small test program; I am caught up in other things for now. In the meantime, you should be able to reproduce this as-is using https://github.com/gergoerdi/scottcheck/tree/c48bb38c3c99e8e89301e37267ee009063ff62ea, with the `games/t04.sao` input file.

**Comment by LeventErkok** [comment]
Thanks @gergoerdi 

@doyougnu Jeff: Is this something you can profile without paying much attention to the details? Let's see where the time suck happens, and maybe something will jump out at us. (Feel free to treat the program as black-box at this point, let's see if there's any low-hanging-fruit first.)

**Comment by doyougnu** [comment]
Looking over the project I don't think it will be problematic to benchmark. Benchmarking `sbv` through an external program is how I got started benchmarking `sbv` in the first place :). The strategy would be to add manual cost centers on the array functions in the `sbv` submodule and benchmark the entire project, using either gauge or criterion, and observing the differences between the `SArray` and `Array` results. Even with the automatic cost centers, e.g., passing `fprof-auto` to ghc you would still see `sbv` functions in the `.prof` report and so detecting `sbv` hot spots exercised by the project code would be pretty straight forward. 

Unfortunately I am also quite swamped at the moment feverishly working towards a paper deadline on the 31st of July. So I probably will not have time to look at this in detail until this deadline has passed.

**Comment by LeventErkok** [comment]
@doyougnu Thanks Jeff.. I think it's perfectly reasonable to delay this after your paper comes out! No worries at all. Best of luck with the writing.

**Comment by doyougnu** [comment]
Alright I finally had a chance to look at this. I didn't get around to benchmarking it because @gergoerdi I could not get https://github.com/gergoerdi/scottcheck/tree/c48bb38c3c99e8e89301e37267ee009063ff62ea to run:

```
❯ stack exec -- scott-check -i games/t4.sao
scott-check:
*** Data.SBV: Unexpected response from the solver, context: getModel:
***
***    Sent      : (get-value (s59))
***    Expected  : a value binding for kind: SMaybe Bool
***    Received  : (error "line 193 column 16: model is not available")
***
***    Executable: z3
***    Options   : -nw -in -smt2
***
***    Reason    : Solver returned an error: "line 193 column 16: model is not available"
```

My hypothesis though is that by _not_ using `SArray` you are generating easier constraints to solve. From the c48bb38c3c99e8e89301e37267ee009063ff62ea commit two things are clear:

1. In the `Array` case, (.!) is calling `select` from the `Mergeable SInt16` instance to do the indexing into the Array.
2. In the `SArray` case this has been replaced with several functions that call `readArray` and `writeArray` from `sbv`. 

This leads me to think that if we checked the SMT output we would see the difference in the constraints received by the solver, and I would bet that we would see more expensive constraints for the `SArray` case. Another thing that stuck out to me was this function:

```
fillArray :: (Ix a, SymArray sarr, SymVal a, SymVal b) => Array a b -> sarr a b -> sarr a b
fillArray arr sarr = foldr write sarr (A.assocs arr)
  where
    write (i, x) sarr = writeArray sarr (literal i) (literal x)
```

I think you only call this function once but it is likely to create a huge amount of thunks because `foldr` is non-strict in the accumulator, similar to the classic memory leak case of `foldr (+) 0 [1..1000]`. The other thing about this function that catches my eye is that it'll be translated to a ton of constraints on the symbolic array in the SMT solver that I don't think exist in the Array case and thus may make the problem harder for the backend solver to solve. We would have to generate the SMT output to be sure though.

I went ahead and tried to test that `select` was slower than `SArray` by constructing a list of length n, then reading m times. Note that this doesn't test any insertion behavior after the initial construction.

### The Bench Program
```
module Main where

import           Gauge.Main.Options (defaultConfig, Config(..))
import           Gauge
import           Data.SBV
import           Data.Bifunctor
import           System.Random

main :: IO ()
main = do
  -- generate the benchmark file name
  -- let f = benchResultsFile "<your-test-name-here>"
  let
    inOrder = [5,50,150,500]
    mkIndices xs = ($ [1..]) . take <$> xs
    [five,fifty,onefifty,fiveHundred] = mkIndices inOrder

    randGenerator = mkStdGen 1726
    -- generate a stream of values between 1 and x and take that many values
    -- from the stream
    randomOrder :: Int -> [Int]
    randomOrder x = take x $ randomRs (1,x) randGenerator
    [fiveR,fiftyR,onefiftyR,fiveHundredR] = randomOrder <$> [5,50,150,500]

  -- Your code on interest here
  defaultMain $
    [ bgroup "Select" [ bench "10 5"     $ nfIO $ testSelect 10   five
                      , bench "100 50"   $ nfIO $ testSelect 100  fifty
                      , bench "1000 150" $ nfIO $ testSelect 1000 onefifty
                      , bench "1000 500" $ nfIO $ testSelect 1000 fiveHundred
                      ]

    , bgroup "SArray" [ bench "10 5"     $ nfIO $ testSArray 10   five
                      , bench "100 50"   $ nfIO $ testSArray 100  fifty
                      , bench "1000 150" $ nfIO $ testSArray 1000 onefifty
                      , bench "1000 500" $ nfIO $ testSArray 1000 fiveHundred
                      ]

    , bgroup "Rand/Select" [ bench "10 5"     $ nfIO $ testSelect 10   fiveR
                           , bench "100 50"   $ nfIO $ testSelect 100  fiftyR
                           , bench "1000 150" $ nfIO $ testSelect 1000 onefiftyR
                           , bench "1000 500" $ nfIO $ testSelect 1000 fiveHundredR
                           ]

    , bgroup "Rand/SArray" [ bench "10 5"     $ nfIO $ testSArray 10   fiveR
                           , bench "100 50"   $ nfIO $ testSArray 100  fiftyR
                           , bench "1000 150" $ nfIO $ testSArray 1000 onefiftyR
                           , bench "1000 500" $ nfIO $ testSArray 1000 fiveHundredR
                           ]

    ]

testSelect :: Int -> [Int] -> IO [SInt16]
testSelect n ms = runSMT $ do
  ar      <- traverse (sInt16 . show) [1..n]
  indices <- traverse (sInt16 . show) ms
  return $ select ar (head ar) <$> indices

fillArray :: (SymArray sarr, SymVal a, SymVal b) => [(a,b)] -> sarr a b -> sarr a b
fillArray arr sarr = foldr write sarr  arr
  where
    write (i, x) sarr' = writeArray sarr' (literal i) (literal x)

testSArray :: Int -> [Int] -> IO [SInt16]
testSArray n ms = runSMT $ do
  emptyArray <- newArray "dummy" Nothing

  let
    assocs :: [(Int16, Int16)]
    assocs = bimap fromIntegral fromIntegral <$> zip [1..n] [2..n+1]

    ar :: SArray Int16 Int16
    ar = fillArray assocs emptyArray

  indices <- traverse (sInt16 . show) ms
  return $ readArray ar <$> indices
```

I checked both just a reading the first `m` elements and `m` elements randomly distributed. Read this as `<Method>/<Array Size> <Num Reads>`, so `Select/10 5` does 5 reads on an array of size 10 with Select. Note that I say array but I just used a List, this shouldn't matter because the code under question always converts the arrays to a list:

```
benchmarked Select/10 5
time                 20.74 μs   (20.27 μs .. 21.16 μs)
                     0.996 R²   (0.992 R² .. 0.998 R²)
mean                 21.05 μs   (20.82 μs .. 21.55 μs)
std dev              1.101 μs   (621.5 ns .. 1.855 μs)
variance introduced by outliers: 30% (moderately inflated)

benchmarked Select/100 50
time                 180.6 μs   (177.9 μs .. 185.2 μs)
                     0.995 R²   (0.991 R² .. 0.999 R²)
mean                 180.8 μs   (179.2 μs .. 183.3 μs)
std dev              6.913 μs   (5.237 μs .. 9.905 μs)
variance introduced by outliers: 20% (moderately inflated)

benchmarked Select/1000 150
time                 1.774 ms   (1.749 ms .. 1.815 ms)
                     0.996 R²   (0.991 R² .. 0.999 R²)
mean                 1.769 ms   (1.752 ms .. 1.791 ms)
std dev              64.94 μs   (47.15 μs .. 87.14 μs)
variance introduced by outliers: 18% (moderately inflated)

benchmarked Select/1000 500
time                 3.315 ms   (3.241 ms .. 3.413 ms)
                     0.996 R²   (0.993 R² .. 0.999 R²)
mean                 3.243 ms   (3.209 ms .. 3.292 ms)
std dev              133.1 μs   (98.15 μs .. 198.8 μs)
variance introduced by outliers: 21% (moderately inflated)

benchmarked SArray/10 5
time                 12.78 μs   (12.61 μs .. 12.96 μs)
                     0.994 R²   (0.988 R² .. 0.999 R²)
mean                 12.98 μs   (12.83 μs .. 13.25 μs)
std dev              638.9 ns   (423.7 ns .. 930.3 ns)
variance introduced by outliers: 29% (moderately inflated)

benchmarked SArray/100 50
time                 65.42 μs   (64.01 μs .. 67.30 μs)
                     0.993 R²   (0.983 R² .. 0.999 R²)
mean                 65.46 μs   (64.74 μs .. 66.44 μs)
std dev              2.783 μs   (1.849 μs .. 3.825 μs)
variance introduced by outliers: 23% (moderately inflated)

benchmarked SArray/1000 150
time                 241.2 μs   (230.3 μs .. 253.7 μs)
                     0.989 R²   (0.983 R² .. 0.998 R²)
mean                 242.2 μs   (238.4 μs .. 253.1 μs)
std dev              19.09 μs   (8.772 μs .. 41.57 μs)
variance introduced by outliers: 50% (moderately inflated)

benchmarked SArray/1000 500
time                 681.6 μs   (663.1 μs .. 703.8 μs)
                     0.994 R²   (0.990 R² .. 0.999 R²)
mean                 695.5 μs   (684.5 μs .. 716.6 μs)
std dev              51.06 μs   (28.68 μs .. 95.02 μs)
variance introduced by outliers: 48% (moderately inflated)

benchmarked Rand/Select/10 5
time                 20.76 μs   (20.37 μs .. 21.12 μs)
                     0.994 R²   (0.987 R² .. 0.999 R²)
mean                 21.14 μs   (20.84 μs .. 21.79 μs)
std dev              1.484 μs   (808.7 ns .. 2.676 μs)
variance introduced by outliers: 44% (moderately inflated)

benchmarked Rand/Select/100 50
time                 182.7 μs   (179.2 μs .. 188.9 μs)
                     0.994 R²   (0.986 R² .. 0.999 R²)
mean                 180.7 μs   (179.3 μs .. 183.1 μs)
std dev              6.261 μs   (4.233 μs .. 10.11 μs)
variance introduced by outliers: 16% (moderately inflated)

benchmarked Rand/Select/1000 150
time                 1.808 ms   (1.739 ms .. 1.895 ms)
                     0.988 R²   (0.976 R² .. 0.997 R²)
mean                 1.850 ms   (1.807 ms .. 1.997 ms)
std dev              234.4 μs   (72.70 μs .. 510.4 μs)
variance introduced by outliers: 74% (severely inflated)

benchmarked Rand/Select/1000 500
time                 3.313 ms   (3.278 ms .. 3.350 ms)
                     0.998 R²   (0.995 R² .. 0.999 R²)
mean                 3.256 ms   (3.222 ms .. 3.294 ms)
std dev              116.6 μs   (90.36 μs .. 154.9 μs)
variance introduced by outliers: 17% (moderately inflated)

benchmarked Rand/SArray/10 5
time                 12.97 μs   (12.74 μs .. 13.29 μs)
                     0.995 R²   (0.990 R² .. 0.999 R²)
mean                 12.95 μs   (12.83 μs .. 13.13 μs)
std dev              498.6 ns   (313.0 ns .. 759.4 ns)
variance introduced by outliers: 20% (moderately inflated)


benchmarked Rand/SArray/100 50
time                 64.55 μs   (63.35 μs .. 66.00 μs)
                     0.996 R²   (0.994 R² .. 0.998 R²)
mean                 65.51 μs   (64.76 μs .. 66.76 μs)
std dev              3.098 μs   (1.988 μs .. 4.842 μs)
variance introduced by outliers: 27% (moderately inflated)

benchmarked Rand/SArray/1000 150
time                 241.7 μs   (235.7 μs .. 249.7 μs)
                     0.995 R²   (0.991 R² .. 0.999 R²)
mean                 240.1 μs   (238.0 μs .. 243.7 μs)
std dev              9.380 μs   (6.193 μs .. 16.65 μs)
variance introduced by outliers: 20% (moderately inflated)

benchmarked Rand/SArray/1000 500
time                 684.4 μs   (675.3 μs .. 694.8 μs)
                     0.998 R²   (0.996 R² .. 0.999 R²)
mean                 686.7 μs   (681.9 μs .. 694.0 μs)
std dev              20.59 μs   (15.57 μs .. 29.24 μs)
variance introduced by outliers: 13% (moderately inflated)
```

So two conclusions:
1. Random reads don't matter compared to linear reads
2. By this benchmark `SArray` is actually much faster (100x!!) than `select`.

**Comment by gergoerdi** [comment]
I have done some rewritings on my end to speed things up quite a lot (mostly by changing the branching structure of `performMatching`); the new version is at https://github.com/gergoerdi/scottcheck/tree/c6524bfbf1eaeedaf247701ebfde3446ff1c16e3 (for `SArray`) and I have tested it with the SBV version included in its `stack.yaml` file so it really should work with no issues. Please try this version and let me know if you still have problems running it out of the box.

**Comment by doyougnu** [comment]
```
❯ git checkout sarray
M	stack.yaml
M	stack.yaml.lock
Branch 'sarray' set up to track remote branch 'sarray' from 'origin'.
Switched to a new branch 'sarray'
❯ stack build
ScottCheck> configure (exe)
Configuring ScottCheck-0.1.0...
ScottCheck> build (exe)
Preprocessing executable 'scott-check' for ScottCheck-0.1.0..
Building executable 'scott-check' for ScottCheck-0.1.0..
[5 of 7] Compiling ScottCheck.Utils
[6 of 7] Compiling ScottCheck.Engine
[7 of 7] Compiling Main
Linking .stack-work/dist/x86_64-linux-nix/Cabal-3.0.1.0/build/scott-check/scott-check ...
ScottCheck> copy/register
Installing executable scott-check in /home/doyougnu/scottcheck/.stack-work/install/x86_64-linux-nix/0180309db9d16d6642dd53f8dfd4e33e5599758a0e89fecbc2c34a9c49fb25e3/8.8.3/bin
❯ stack exec -- scott-check -i "games/t4.sck"
scott-check: src/main.hs:133:9-40: Non-exhaustive patterns in Right theGame
```
What am I missing here?

**Comment by gergoerdi** [comment]
Please run it on `games/t4.sao`, not `games/t4.sck`. 

In case you don't have `scottkit` installed so you aren't able to `make` `t4.sao` from `t4.sck`, you can get the pre-made `t4.sao` from https://gergo.erdi.hu/files/t4.sao

**Comment by gergoerdi** [comment]
I've changed the definition of `fillArray` to use `foldl'` and it seems to speed things up a bit:

# `SArray`, lazy `fillArray`:

```
00:00 Searching at depth: 1
00:00 Searching at depth: 2
00:00 Searching at depth: 3
00:00 Searching at depth: 4
00:01 Searching at depth: 5
00:01 Searching at depth: 6
00:03 Searching at depth: 7
00:06 Searching at depth: 8
00:16 Searching at depth: 9
00:51 Searching at depth: 10
01:23 Searching at depth: 11
01:44 Searching at depth: 12
03:23 Searching at depth: 13
04:13 Searching at depth: 14
05:58 Solution found:
05:58   1. GO WES
05:58   2. GET CRO
05:58   3. GO EAS
05:58   4. GO NOR
05:58   5. GET KEY
05:58   6. GO SOU
05:58   7. OPE DOO
05:58   8. GO DOO
05:58   9. GET COI
05:58  10. GO NOR
05:58  11. GO WES
05:58  12. GO NOR
05:58  13. DRO COI
05:58  14. SCO ANY
	Command being timed: "scott-check games/t4.sao"
	User time (seconds): 357.78
	System time (seconds): 0.53
	Percent of CPU this job got: 100%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 5:57.91
```

# `SArray`, strict `fillArray`

```
00:00 Searching at depth: 1
00:00 Searching at depth: 2
00:00 Searching at depth: 3
00:00 Searching at depth: 4
00:01 Searching at depth: 5
00:01 Searching at depth: 6
00:02 Searching at depth: 7
00:04 Searching at depth: 8
00:08 Searching at depth: 9
00:19 Searching at depth: 10
00:50 Searching at depth: 11
01:18 Searching at depth: 12
02:44 Searching at depth: 13
04:31 Searching at depth: 14
06:29 Solution found:
06:29   1. GO WES
06:29   2. GET CRO
06:29   3. GO EAS
06:29   4. GO NOR
06:29   5. GET KEY
06:29   6. GO SOU
06:29   7. OPE DOO
06:29   8. GO DOO
06:29   9. GET COI
06:29  10. GO NOR
06:29  11. GO WES
06:29  12. GO NOR
06:29  13. DRO COI
06:29  14. SCO ANY
	Command being timed: "scott-check games/t4.sao"
	User time (seconds): 389.10
	System time (seconds): 0.50
	Percent of CPU this job got: 100%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 6:29.36
```

**Comment by LeventErkok** [comment]
Thanks for all the work Jeff!

This seems to be in line with my expectations:

  - `SFunArray` should take more SBV time to process, but hopefully produces simpler formulas for the backend solver
  - `SArray` is easier for SBV to generate, but possibly can generate harder problems for the backend solver

(The original motivation for SFunArray was precisely to support solvers that didn't have support for arrays when SBV first started. I belive that list has significantly diminished in the meantime and maybe it's only ABC and dReal that doesn't support them now.)

But of course, the trick is figuring out exactly when to use which. (Or even do a mix&match for different parts of the problem.) This is where symbolic programming becomes more of an art than science. I wish I had clear guideliness on when to use which, but I don't. (For instance in the HexPuzzle example, `SFunArray` is a huge win over `SArray`. But for this Scott-game problem, it's not at all clear which one is better.)

**Comment by LeventErkok** [comment]
I'm guessing this is no longer an issue. Symbolic arrays are a soft spot for performance, both for inherent reasons and possibly due to some implementation issues in SBV itself as well. But without an explicit (and small!) test case to go on, there isn't much of an actionable item to pursue here.

Feel free to reopen (or file a new issue) as needed and/or if there's more data to share.
