### ISSUE TITLE
Could not find module ‘Data.SBV’ after stack install sbv

### ISSUE THREAD

**Issue by JivanRoquet** [LeventErkok/sbv#564]
I followed the steps below to install and test sbv, using macOS version 11.0 Beta (20A5343j).

Importing `Data.SBV` triggers an error `Could not find module 'Data.SBV'`.

```shell
# from the shell
stack install sbv

# no error during the installation — all the following packages were installed
# (copy/pasting the "using precompiled package" for brevity)

# FloatingHex> using precompiled package
# hashable   > using precompiled package
# random     > using precompiled package
# syb        > using precompiled package
# crackNum   > using precompiled package
# async      > using precompiled package
# splitmix   > using precompiled package
# QuickCheck > using precompiled package
# sbv        > using precompiled package


# from ghci
λ> import Data.SBV
<no location info>: error:
    Could not find module ‘Data.SBV’
    Perhaps you meant
      Data.Set (needs flag -package-key containers-0.6.2.1)
```

I've tested both in the global stack environment, and also in a brand new stack project, same outcome.

Is there some additional step that I wouldn't know?

Possibly related:
- https://github.com/NixOS/nixpkgs/issues/4652
- https://gist.github.com/LeventErkok/1715097

**Comment by LeventErkok** [comment]
I don’t use stack, so I’m not particularly familiar with it. Can you install using regular cabal?

If you must use stack, see if this is an SBV only problem, i.e., if you can install other packages fine. Otherwise you might want to ask at stackoverlow for some stack guidance. 

Typically `cabal new-install  sbv -–lib` is the way to go.

**Comment by JivanRoquet** [comment]
Thanks for the reactivity.

I have posted a question on StackOverflow, here's a link to it for posterity https://stackoverflow.com/questions/64518276/module-works-with-cabal-but-not-with-stack

I will include any useful information here if (hopefully) that comes up.

**Comment by doyougnu** [comment]
Hi Jivan,

This is probably not related to `sbv`; what OS are you using? If you are on NixOS (which I guess you might be based on your possibly related link) then you'll need to tell `stack` (or `cabal` for that matter) that you are on nix. You can do this in `stack.yaml` with a simple:

```
nix:
  enable: true
```

Other than that stack may complain that it cannot find `sbv` if you are using an `lts` stackage version that does not contain `sbv`. Stack _does not_ pull packages from `hackage` like `cabal` does, rather it pulls packages from `Stackage`. Stackage is Hackage but uses a set of packages which are known working with each other to avoid dependency conflicts and dependency hell. You can check to see which version you are using in `stack.yaml` under `resolver` for example I might have:

```
# in stack.yaml
resolver: resolver: lts-16.19
```

which instructs stack to use the `stackage-server` `lts-16.19`, which you can lookup [here](https://www.stackage.org/lts-16.19). From that site I can then lookup to see what version of `sbv` I'm getting. Because this lts version is pretty new `sbv` isn't listed, meaning that `sbv` isn't in the `stackage` package set and thus to use it I would need to add it under `extra-deps` in the `stack.yaml` file. If I failed to do that then stack would complain that `sbv` was not found.

Could you please say what OS you are using and post your `stack.yaml` and `package.yaml`?

**Comment by JivanRoquet** [comment]
Hi @doyougnu. Thanks for your contribution. It does not seem to be a Stack-specific issue, as other external packages work perfectly well when following the exact same steps. This issue only happened with `sbv` so far, and I believe it is related to it not being available on Stackage.

I'm not entirely clear as to what to specify exactly in `stack.yaml` yet. I tried doing the following:

```yaml
extra-deps:
    - git: https://github.com/LeventErkok/sbv.git
    commit: 4f4baa7b5970ef2ab9b322c6694bf9df6ccdbc4b
```

and running `stack ghci` but then Stack still cannot import `Data.SBV`.

Once thing that worked, has been to run ghci by specifying `stack ghci --package sbv` after having installed it, but I still can't manage to include `sbv` in my stack build in a proper manner.

Also, I'm using macOS — the NixOS link was just a reference to the same problem, which happened to be with a Nix user (not my case).

**Comment by doyougnu** [comment]
Ah ok. So the `stack.yaml` is providing information to `stack` for a particular project. If you invoke `stack ghci` while in a directory that has a `stack.yaml` file then `stack` will use that file for the `ghci` instance you are trying to create. 

So are you calling `stack ghci` from a directory that has the `stack.yaml` file? If not then stack will use your global configuration which you can find in your home directory: `~/.stack/global-project/stack.yaml`. These files may have different `resolver` values in `stack.yaml` and therefore will be pointing to different package sets. So because `stack ghci --package sbv` works but `stack ghci` from your directory doesn't (if you did indeed invoke `stack ghci` from your project root) I bet you have a different `resolver` for your global configuration than for your project configuration, with the project configuration resolver not having `sbv`.

Some relevant links for you:
  - the `stack.yaml` vs `cabal` file section of the stack [manual](https://docs.haskellstack.org/en/stable/stack_yaml_vs_cabal_package_file/)
  - the project-specific-configuration section of the [manual](https://docs.haskellstack.org/en/stable/yaml_configuration/#project-specific-config)

You might also try pointing your `extra-deps` to a previous release of `sbv` instead of `master` just in case. For example commit 9c20cf9ab2c4ed2cc0ed867a9bd5d496571f0b1e is for the `8.6` release.

**Comment by JivanRoquet** [comment]
All solved. It was probably due to a difference in resolvers, as you pointed.

What solved the issue was adding this in `stack.yaml`

```yaml
extra-deps:
  - git: https://github.com/LeventErkok/sbv.git
    commit: 4f4baa7b5970ef2ab9b322c6694bf9df6ccdbc4b
```

and this is `project.cabal`

```haskell
executable project
  build-depends: sbv
```

**Comment by LeventErkok** [comment]
I'm glad this got resolved. Thanks for the info Jeff, very helpful.

I personally don't use stack since latest versions of packages are typically not on it. For instance, I believe the latest sbv on stackage is 8.3; which is well over a year old at this point. (Hackage has v8.8, and I'm planning 8.9 in the next week or two.) So beware of any bugs and/or missing features these old versions might have.

(I used to try to keep stackage "up-to-date" as well, but I gave up a few years ago; because your package on it becomes obsolete just because some other package you depend on becomes not-compatible. I understand the philosophy behind stackage, but it's too restrictive for my use model. Your mileage may vary, of course.)
