### ISSUE TITLE
Possibility to generate a satisfying solution at random

### ISSUE THREAD

**Issue by JivanRoquet** [LeventErkok/sbv#565]
A given use case requires constructing a set of satisfiable solutions, and pick one at random among this set. Currently, I do this by choosing a random number `n` upfront between 0 and (say) 1,000 — then I query `runSMT` and I have it loop `n` times to find successive satisfying solutions, then I return the `n-th` one.

Example, if `n` is randomly chosen as 42, then `runSMT` iterates through the first 42 solutions, adding a constraint that rejects each one in turn, and returns the last one. The problem with this approach is that if the random number is high (e.g. 500) then the time to compute all the 499 intermediate (and, for my purposes, useless) solutions becomes big (several minutes).

Is there a way to ask for a "random" satisfying solution other than what I described above, or to compute several satisfying solutions at once (maybe in parallel) and return either all of them or a random one?

I don't think there's currently any such capability built in SBV, however would Z3 (or other backends) allow it in principle, or would it be fundamentally infeasible?

**Comment by LeventErkok** [comment]
This isn't something SBV or any SMT solver that I know of supports.

The problem is also known as "uniform sampling" of solutions; because an SMT solver has no obligation to return you a "random" solution. If you ask it to give you an integer between `0` and `100`, it'll happily go through `0, 1, 2, ... 100` in that order, while your use case would like it to produce `55, 42, 12, 78.." i.e., a random sampling. This isn't supported by z3 or any other SMT solver, but you *can* code it up on top. But finding a good sampling is not an easy task.

Some relevant discussions:

  https://stackoverflow.com/questions/39220169/using-z3-to-sample-from-a-constrained-space
  https://stackoverflow.com/questions/12734672/sample-uniformly-from-set-of-satisfying-assignments-in-z3/12746087#12746087
 https://stackoverflow.com/questions/49224465/obtaining-representation-of-smt-formula-as-sat-formula

Some suggestions from Nikolaj (restricted to BVs): https://github.com/Z3Prover/z3/issues/4675

Good luck!

**Comment by JivanRoquet** [comment]
Thanks for your guidance.

This is what I was thinking. As no solver currently supports this, I'm assuming this is either not a demanded enough use case (which means there are probably better ways to handle this than at this level), or there is some kind of fundamental technical impediment to it.

In any case, I've gone with the former option and ended up implementing a Redis cache which gets populated with thousands of iterated solutions, which the rest of code chooses a random element from. Obviously this is faster than any solver-based solution, although it requires having some form of "staticity" in the constraints (i.e. couldn't work with an entirely dynamic set of constraints).

Best,

**Comment by LeventErkok** [comment]
Yes; this is definitely a problem that is an active research area, and there's no good out-of-the-box solution right now. You can see Rafael's recent work in this area: https://people.eecs.berkeley.edu/~rtd/.

In particular, this paper is quite relevant: https://people.eecs.berkeley.edu/~rtd/papers/GuidedSampler.pdf
