### ISSUE TITLE
Cannot prove "1000"  `match` Loop 1 4 $ Range '0' '9'

### ISSUE THREAD

**Issue by yaitskov** [LeventErkok/sbv#596]
Hi,

```
prove $ \(i :: SInteger) -> (i .< 1000 .&& i .> -1000) .=> (natToStr i) `match` (Conc [Opt $ Literal "-", Loop 1 4 (Range '0' '9')])
Falsifiable. Counter-example:
  s0 = -2 :: Integer
-- but works
prove $ \(i :: SInteger) -> (i .> -1000 .&& i .< 1000) .=> (natToStr i) `match` (Conc [Opt $ Literal "-" , KStar (Range '0' '9')])
Q.E.D.
```
I guess there is an error by -1 because following works

```
 prove $ \(i :: SInteger) -> (i .< 1000 .&& i .> -1000) .=> (natToStr i) `match` (Conc [Opt $ Literal "-", Loop 0 3 (Range '0' '9')])
Q.E.D.
```

Nonetheless original pattern matches literal constant as expected:

```
prove $ \(i :: SInteger) -> ("-1000" :: SString) `match` (Conc [Opt $ Literal "-", Loop 1 4 (Range '0' '9')])
<interactive>:68:11: warning: [-Wunused-matches]
    Defined but not used: ‘i’
Q.E.D.
```

**Comment by LeventErkok** [comment]
The function `natToStr` only accepts positive integers. If given a negative value, the result is the empty string. This follows the SMTLib standard, and is documented in http://smtlib.cs.uiowa.edu/theories-UnicodeStrings.shtml. Note that SBV's `natToStr` is SMTLib's `str.from_int`. The document says:

> ; Conversion to integers
       ; (str.to_int s) with s consisting of digits (in the sense of str.is_digit)
       ; evaluates to the positive integer denoted by s when seen as a number in 
       ; base 10 (possibly with leading zeros).
       ; It evaluates to -1 if s is empty or contains non-digits. 
       (str.to_int String Int)

And further give the example:

>  (str.from_int -123) evaluates to """", an error value, not to ""-123"".

The very same fact is also documented in SBV's own documentation, here: https://hackage.haskell.org/package/sbv-8.16/docs/Data-SBV-String.html#g:5:

<img width="203" alt="Screen Shot 2021-09-30 at 8 31 40 AM" src="https://user-images.githubusercontent.com/549449/135485954-51cf9cf4-d02c-4e11-8f96-82c94cc7cf56.png">

So, to sum up, given a negative value, the semantics of `natToStr` is to produce an empty string. (Hence the name `natToStr`, to indicate that the input must be a natural number, i.e., at least 0).

Based on this:

- Your first example is indeed falsifiable, because the conversion produces empty string, which does not match the regular expression; as it requires at least one digit.
- Similarly, second example works because your regular expression now matches the empty string.
- Your last example works because there's no conversion; you just have a regular string and it does indeed match the regular expression.

So, I don't see any problems here. Looks like it's working as intended.

Note that SBV allows you to "observe" values of subexpressions that can come in handy in these cases:

```haskell
Prelude Data.SBV Data.SBV.RegExp Data.SBV.String> prove $ \(i :: SInteger) -> (i .< 1000 .&& i .> -1000) .=> observe "converted" (natToStr i) `match` (Conc [Opt $ Literal "-", Loop 1 4 (Range '0' '9')])
Falsifiable. Counter-example:
  converted = "" :: String
  s0        = -2 :: Integer
```

You can have as many `observe` nodes as you like, and they'll be presented in the model if there's any.

If you want you can have your own version of integer to string conversion, by coding it yourself:

```haskell
import Data.SBV
import Data.SBV.RegExp
import Data.SBV.String

intToStr :: SInteger -> SString
intToStr x = ite (x .< 0)
                 (literal '-' .: (natToStr (-x)))
                 (natToStr x)
```

But be aware that these sort of constructions can give the solver a hard time; i.e., mixing integer arithmetic and strings will probably not that efficient. Indeed:

```haskell
*Main> prove $ \(i :: SInteger) -> (i .< 3 .&& i .> -3) .=> (intToStr i) `match` (Conc [Opt $ Literal "-", Loop 1 4 (Range '0' '9')])
Q.E.D.
```

But changing the range from `(-3, 3)` to your original `(-1000, 1000)` takes much longer for z3 to come back. (I didn't wait!)

Hope all this helps..

**Comment by LeventErkok** [comment]
One last note.. We have an `sbv` tag on stack-overflow. Questions like this might be more suitable there so it reaches a wider audience on pitfalls like this: https://stackoverflow.com/questions/tagged/sbv

**Comment by yaitskov** [comment]
@LeventErkok thanks for detailed explanation. 
My newbie insight for maintainer on this problem - I didn't expect that natToStr cannot handle negatives, because argument type is an Integer (nonetheless I knew that Nat is 0 or succ 0). I would at least use a type alias SWord or SNat instead of SInteger for the argument. This would reduce changes for other application developers to be caught by this subconscious trick.

**Comment by LeventErkok** [comment]
Having an alias of `SNat` for `SInteger` is  misleading at best; since there's no way for SBV to ensure it won't be negative. Unless SMTLib gains a natural type, we're stuck using `SInteger` for natural numbers.

Of course, you can always define your own type-alias in your own code, if that's something you'd prefer.
