### ISSUE TITLE
Overlapping instance `Queriable m (t (SBV a))`

### ISSUE THREAD

**Issue by ocramz** [LeventErkok/sbv#719]
GHC 9.6.5

Hi there,
I just ran into an Overlapping Instance between `Queriable m (t (SBV a))` and a custom `Queriable` instance over a Traversble type I'm defining (the Traversable instance is to blame, but I need it elsewhere).

It can be apparently solved by adding an `{-# OVERLAPPING #-}` pragma to the custom instance, but apparently another way would be for `sbv` to provide its own instance as `{-# OVERLAPPABLE #-}`. https://serokell.io/blog/learn-from-errors-overlapping-instances

Any thoughts?

**Comment by LeventErkok** [comment]
Sure.. Pushed to head. Does that solve your problem?

**Comment by ocramz** [comment]
I think so, thank you so much! 🙏 

In passing, I noticed CI only runs against GHC 9.10 (latest), and seeing the .. healthy evolution of the compiler I imagine some users of older versions might be impacted.

**Comment by LeventErkok** [comment]
Glad to hear..

I wish SBV had a better CI strategy; with more OS's, more GHC versions, and also running tests. Unfortunately that requires installment of (at least one) solver on the CI machine, and lots of infrastructure build and when I last tried it 4-5 years ago, the time-limits on public machines weren't enough to run tests in any meaningful way. For instance, when you "install" solvers latest versions tests usually fail for bad reasons: Because you get a different model. (Not because the test actually gets the wrong result.)

So, I simply set CI to be the version I use for my own development, matching the version that actually got not only built, but ran the tests against. This isn't ideal, but it's an honest statement.

Any contributions regarding building of a much more beefed of CI would be welcome. But I'm also wondering if there's enough ROI there. With the man-power I have, the current situation is the best compromise I can come up with.

**Comment by ocramz** [comment]
We're using Z3 in a project and a naive `apt-get install z3` (takes a few seconds) followed by `stack test` for our sbv tests works like a charm.
