### ISSUE TITLE
Design: Wp: wpProveWith: user-supplied initial state rather than a randomly generated one

### ISSUE THREAD

**Issue by ocramz** [LeventErkok/sbv#725]
I often `trace` my programs together with `wpProveWith` , which means I have one or more initial states to test. Wouldn't it make sense to let a user pass their own initial state, to compare the outcome of tracing and WP side by side?

https://github.com/LeventErkok/sbv/blob/master/Data/SBV/Tools/WeakestPreconditions.hs#L215

**Comment by LeventErkok** [comment]
The initial state is supposed to be constrained by `precondition`.

If you're running on a concrete state, simply program so that `precondition` is essentially `== startingState`.
If you want to run with many starting conditions, you can even do `\st -> st `elem` allStartingStates`; or encode the starting states in this predicate.

Also, if your starting state is completely concrete, then you should simply use `traceExecution`. (Or better yet, write your own interpreter, why do you even need the prover in that case?)
