### ISSUE TITLE
Unknown constant seq.foldl when using SBV.List.all

### ISSUE THREAD

**Issue by amigalemming** [LeventErkok/sbv#728]
~~~~
ghci> import qualified Data.SBV.List as SList
ghci> import Data.SBV as SBV
ghci> prove (\xs -> sNot (SList.all id xs) .== SList.any sNot xs)
*** Exception: 
*** Data.SBV: Unexpected non-success response from Z3:
***
***    Sent      : (define-fun s1 () Bool (seq.foldl (lambda ((l1_s0 Bool) (l1_s1 Bool))
***                  (and l1_s0 l1_s1)) true s0))
***    Expected  : success
***    Received  : (error "line 12 column 28: unknown constant seq.foldl ((Array Bool Bool Bool) Bool (Seq Bool)) ")
***
***    Exit code : ExitFailure (-15)
***    Executable: /usr/bin/z3
***    Options   : -nw -in -smt2
***
***    Reason    : Check solver response for further information. If your code is correct,
***                please report this as an issue either with SBV or the solver itself!
~~~~

This looks like a bug, but maybe I expect to much of the `SList` type. Maybe it is only intended for lists with concrete elements but not for symbolic lists?

**Comment by LeventErkok** [comment]
`seq.foldl` is a fairly new addition to z3; I assume you have an old version of z3 installed that doesn't support it. (See https://microsoft.github.io/z3guide/docs/theories/Sequences/). I'm personally using:

```
$ z3 --version
Z3 version 4.13.4 - 64 bit
```

If you upgrade your z3 version (the latest official release should do it) you'll see that you no longer get the error:

```haskell
ghci> import qualified Data.SBV.List as SList
ghci> import Data.SBV as SBV
ghci> prove (\xs -> sNot (SList.all id xs) .== SList.any sNot XS)
... does not terminate ...
```

So, it goes through with the latest z3, but it does not terminate. This isn't really surprising, because a proof like this would require induction, and SMT-solvers don't really do induction out-of-the box.

There's a way to code inductive proofs in SBV. Unsurprisingly this requires more work on the user side to write your proof. And since it relies on quantifiers, different solvers perform differently. For your example, I found that z3 is really having a hard-time, but it goes through quickly with CVC5:

```haskell
{-# LANGUAGE DataKinds #-}

import Data.SBV
import qualified Data.SBV.List as L
import Data.SBV.Tools.KnuckleDragger

example :: IO Proof
example = runKDWith cvc5 $ lemma "example" (\(Forall @"xs" xs) -> p xs) [induct p]
  where p xs = sNot (l_all id xs) .== l_any sNot xs

        l_all f = smtFunction "l_all" $ \xs -> ite (L.null xs) sTrue  (f (L.head xs) .&& l_all f (L.tail xs))
        l_any f = smtFunction "l_any" $ \xs -> ite (L.null xs) sFalse (f (L.head xs) .|| l_any f (L.tail xs))
```

When you run this (assuming you've installed a recent version of CVC5), you get:

```haskell
*Main> example
Lemma: example                          Q.E.D.
[Proven] example
```

Note that I didn't use the SBV supplied definitions of `SList.all` and `SList.any`, but instead coded them as recursive-functions. The reason for this is that CVC5 doesn't support `seq.foldl` either, which SBV uses internally. (Perhaps we should also provide these more direct definitions straight from SBV, but that's a different discussion.)

Hope this helps..

**Comment by LeventErkok** [comment]
@amigalemming  I've checked in a few changes; so if you build from GitHub master, you can now say:

```haskell
{-# LANGUAGE DataKinds #-}

import Data.SBV
import qualified Data.SBV.List as L
import Data.SBV.Tools.KnuckleDragger

example :: IO Proof
example = runKDWith cvc5 $ lemma "example" (\(Forall @"xs" xs) -> p xs) [induct p]
  where p xs = sNot (L.all id xs) .== L.any sNot XS
```

And get:

```haskell
*Main> example
Lemma: example                          Q.E.D.
[Proven] example
```

Support for such higher order functions is relatively untested. So, do let me know if you run into any issues.
